import {
  LayoutDashboard,
  FolderKanban,
  HardHat,
  Briefcase,
  DollarSign,
  Calendar,
  FileText,
  ClipboardList,
  Users,
  Building,
  CheckSquare,
  Package,
  TrendingDown,
  TrendingUp,
  Clock,
  Shield,
  BookOpen,
  Target,
  BarChart3,
  FolderOpen,
  Image,
  HardDrive,
  LucideIcon,
  CalendarClock,
  Calculator,
  Mail,
  UserCheck,
  UserPlus,
  MessageSquare,
  Receipt,
  FilePenLine,
  Home,
  Settings,
  HelpCircle,
} from "lucide-react";

export interface ContractorNavItem {
  id: string;
  label: string;
  to?: string;
  icon?: LucideIcon;
  children?: ContractorNavItem[];
  separatorAbove?: boolean;
  requiredRoles?: string[]; // If specified, user must have at least one of these roles
}

export const CONTRACTOR_SIDENAV: ContractorNavItem[] = [
  {
    id: "overview",
    label: "Overview",
    children: [
      {
        id: "portal-home",
        label: "Portal Home",
        to: "/contractor/portal",
        icon: Home,
      },
      {
        id: "dashboard",
        label: "Dashboard",
        to: "/contractor/dashboard",
        icon: LayoutDashboard,
      },
      {
        id: "calendar",
        label: "Calendar",
        to: "/contractor/calendar",
        icon: Calendar,
      },
      {
        id: "messages",
        label: "Messages",
        to: "/contractor/messages",
        icon: MessageSquare,
      },
    ],
  },
  {
    id: "sales-pipeline",
    label: "Sales Pipeline",
    separatorAbove: true,
    children: [
      {
        id: "pipeline-overview",
        label: "Pipeline Board",
        to: "/contractor/sales-pipeline",
        icon: TrendingUp,
      },
      {
        id: "leads",
        label: "Leads",
        to: "/contractor/leads",
        icon: UserPlus,
      },
      {
        id: "estimates-sales",
        label: "Estimates",
        to: "/contractor/estimates",
        icon: Calculator,
      },
    ],
  },
  {
    id: "collections",
    label: "Collections",
    separatorAbove: true,
    children: [
      {
        id: "collections-overview",
        label: "Overview",
        to: "/contractor/collections",
        icon: DollarSign,
      },
      {
        id: "collections-this-week",
        label: "Collected This Week",
        to: "/contractor/collections?view=this-week",
        icon: TrendingUp,
      },
      {
        id: "collections-uncollected",
        label: "Uncollected",
        to: "/contractor/collections?view=uncollected",
        icon: Clock,
      },
    ],
  },
  {
    id: "project-manager",
    label: "Project Manager",
    separatorAbove: true,
    children: [
      {
        id: "pm-dashboard",
        label: "PM Dashboard",
        to: "/contractor/pm-dashboard",
        icon: LayoutDashboard,
        requiredRoles: ["contractor", "project_manager", "admin"],
      },
      {
        id: "project-portal",
        label: "Overview",
        to: "/contractor/project-management",
        icon: FolderKanban,
      },
      {
        id: "timelines",
        label: "Timelines",
        to: "/contractor/timelines",
        icon: TrendingDown,
      },
      {
        id: "project-schedule",
        label: "Schedule",
        to: "/admin/schedule",
        icon: Calendar,
      },
    ],
  },
  {
    id: "team-management",
    label: "Team Management",
    separatorAbove: true,
    requiredRoles: ["admin", "contractor"],
    children: [
      {
        id: "architect-designer",
        label: "Architect/Designer",
        to: "/architect/dashboard",
        icon: Building,
        requiredRoles: ["admin", "contractor", "architect"],
      },
      {
        id: "finance-billing",
        label: "Finance & Billing",
        to: "/finance/dashboard",
        icon: DollarSign,
        requiredRoles: ["admin", "contractor", "finance"],
      },
      {
        id: "estimator-team",
        label: "Estimator",
        icon: Calculator,
        requiredRoles: ["admin", "contractor", "estimator"],
        children: [
          {
            id: "estimator-project-dashboard",
            label: "Project Dashboard",
            to: "/contractor/project-dashboard",
            icon: Calculator,
          },
        ],
      },
      {
        id: "foreman-portal",
        label: "Foreman Portal",
        to: "/contractor/foreman-portal",
        icon: HardHat,
      },
      {
        id: "inside-sales",
        label: "Inside Sales",
        to: "/contractor/inside-sales",
        icon: UserCheck,
        requiredRoles: ["admin", "contractor", "inside_sales", "vp_of_sales"],
      },
      {
        id: "outside-sales",
        label: "Outside Sales",
        to: "/contractor/outside-sales",
        icon: UserPlus,
        requiredRoles: ["admin", "contractor", "outside_sales", "vp_of_sales"],
      },
      {
        id: "project-coordinator",
        label: "Project Coordinator",
        to: "/contractor/coordinator-pipeline",
        icon: CalendarClock,
        requiredRoles: ["contractor", "project_coordinator", "admin"],
      },
      {
        id: "project-manager",
        label: "Project Manager",
        to: "/contractor/project-manager-pipeline",
        icon: HardHat,
        requiredRoles: ["contractor", "project_manager", "admin"],
      },
      {
        id: "pm-appointments",
        label: "Appointment Requests",
        to: "/contractor/pm-appointments",
        icon: CalendarClock,
        requiredRoles: ["contractor", "project_manager", "admin"],
      },
      {
        id: "sub-appointments",
        label: "My Appointments",
        to: "/contractor/subcontractor-appointments",
        icon: CalendarClock,
        requiredRoles: ["foreman", "subcontractor"],
      },
      {
        id: "role-management",
        label: "Role Management",
        to: "/contractor/role-management",
        icon: Shield,
        requiredRoles: ["contractor", "admin"],
      },
      {
        id: "subcontractor",
        label: "Subcontractor",
        to: "/contractor/subcontractor-portal",
        icon: Building,
      },
      {
        id: "team-invitations",
        label: "Team Invitations",
        to: "/contractor/team-invitations",
        icon: Mail,
      },
      {
        id: "team-members",
        label: "Team Members",
        to: "/contractor/team",
        icon: Users,
        requiredRoles: ["contractor_admin"],
      },
      {
        id: "vendor",
        label: "Vendor",
        to: "/contractor/vendors",
        icon: Package,
        requiredRoles: ["admin", "contractor"],
      },
      {
        id: "vendor-performance",
        label: "Vendor Performance",
        to: "/contractor/vendor-performance",
        icon: BarChart3,
        requiredRoles: ["admin", "contractor"],
      },
    ],
  },
  {
    id: "sales-crm",
    label: "Sales & CRM",
    separatorAbove: true,
    children: [
      {
        id: "bids",
        label: "Bids",
        to: "/contractor/bids",
        icon: FileText,
      },
      {
        id: "change-orders-sales",
        label: "Change Orders",
        to: "/contractor/change-orders",
        icon: FilePenLine,
      },
      {
        id: "estimates-sales",
        label: "Estimates",
        to: "/contractor/estimates",
        icon: ClipboardList,
      },
      {
        id: "invoices",
        label: "Invoices",
        to: "/contractor/invoices",
        icon: Receipt,
      },
      {
        id: "lead-tracking",
        label: "Lead Tracking",
        to: "/contractor/lead-tracking",
        icon: Target,
      },
      {
        id: "opportunities",
        label: "Opportunities",
        to: "/contractor/opportunities",
        icon: TrendingUp,
      },
      {
        id: "pricing",
        label: "Pricing",
        to: "/contractor/pricing",
        icon: DollarSign,
      },
      {
        id: "sales-performance",
        label: "Sales Performance",
        to: "/contractor/sales-performance",
        icon: TrendingUp,
      },
      {
        id: "sales-reporting",
        label: "Sales Reporting",
        to: "/contractor/sales-reporting",
        icon: BarChart3,
      },
    ],
  },
  {
    id: "estimator",
    label: "Estimator",
    separatorAbove: true,
    requiredRoles: ["admin", "contractor", "estimator"],
    children: [
      {
        id: "bid-room",
        label: "Bid Room",
        to: "/estimator/bid-room",
        icon: Briefcase,
      },
      {
        id: "estimates-estimator",
        label: "Estimates",
        to: "/estimator/estimates",
        icon: FileText,
      },
      {
        id: "leads",
        label: "Leads",
        to: "/estimator/leads",
        icon: Target,
      },
      {
        id: "bid-submissions",
        label: "My Bids",
        to: "/estimator/bid-submissions",
        icon: FileText,
      },
      {
        id: "walkthroughs",
        label: "Walkthroughs",
        to: "/estimator/walkthroughs",
        icon: ClipboardList,
      },
    ],
  },
  {
    id: "old-team-section",
    label: "Old Team Section",
    separatorAbove: false,
    requiredRoles: ["admin", "contractor", "project_manager"],
    children: [
      {
        id: "contacts-companies",
        label: "Contacts & Companies",
        to: "/contractor/team-management",
        icon: Users,
      },
      {
        id: "insurance-certificates",
        label: "Insurance & Certificates",
        to: "/contractor/insurance-certificates",
        icon: Shield,
      },
      {
        id: "subcontractor-portals",
        label: "Subcontractor Portals",
        to: "/contractor/subcontractor-portal",
        icon: Building,
      },
      {
        id: "time-tracking",
        label: "Time Tracking",
        to: "/contractor/time-tracking",
        icon: Clock,
      },
    ],
  },
  {
    id: "project-tracking",
    label: "Project Tracking",
    separatorAbove: true,
    children: [
      {
        id: "projects",
        label: "All Projects",
        to: "/contractor/projects",
        icon: Briefcase,
      },
      {
        id: "client-selections",
        label: "Client Selections",
        to: "/admin/selections",
        icon: Package,
      },
      {
        id: "daily-logs",
        label: "Daily Logs",
        to: "/contractor/daily-logs",
        icon: BookOpen,
      },
      {
        id: "permit-tracking",
        label: "Permit Tracking",
        to: "/contractor/permit-tracking",
        icon: FileText,
      },
      {
        id: "project-schedule-tracking",
        label: "Project Schedule",
        to: "/admin/schedule",
        icon: Calendar,
      },
      {
        id: "punch-lists",
        label: "Punch Lists",
        to: "/contractor/punch-lists",
        icon: CheckSquare,
      },
      {
        id: "purchase-orders",
        label: "Purchase Orders",
        to: "/contractor/purchase-orders",
        icon: Package,
      },
      {
        id: "smartplan",
        label: "SmartPlan",
        to: "/contractor/smartplan",
        icon: CheckSquare,
      },
      {
        id: "warranty-tracking",
        label: "Warranty Tracking",
        to: "/contractor/warranty-tracking",
        icon: Shield,
      },
    ],
  },
  {
    id: "files-photos",
    label: "Files & Photos",
    separatorAbove: true,
    children: [
      {
        id: "file-management",
        label: "File Management",
        to: "/contractor/file-management",
        icon: FolderOpen,
      },
      {
        id: "photos",
        label: "Photos",
        to: "/contractor/photos",
        icon: Image,
      },
      {
        id: "smartreno-drive",
        label: "SmartReno Drive",
        to: "/contractor/smartreno-drive",
        icon: HardDrive,
      },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    separatorAbove: true,
    children: [
      {
        id: "account-settings",
        label: "Account Settings",
        to: "/contractor/settings",
        icon: Settings,
      },
      {
        id: "help-center",
        label: "Help Center & Demos",
        to: "/contractor/help-center",
        icon: HelpCircle,
      },
    ],
  },
];
