// Comprehensive demo data for contractor portal demo mode

export const getDemoPermitTracking = () => ({
  summary: {
    total: 8,
    approved: 3,
    inProcess: 3,
    pending: 2,
  },
  permits: [
    {
      id: "demo-permit-1",
      project_id: "demo-project-1",
      project_name: "Johnson Kitchen Renovation",
      project_location: "123 Oak Street, Ridgewood, NJ",
      permit_type: "Building Permit",
      municipality: "Bergen County",
      status: "approved",
      application_date: "2024-11-15",
      approval_date: "2024-12-10",
      permit_number: "BP-2024-1234",
      fees: 450,
    },
    {
      id: "demo-permit-2",
      project_id: "demo-project-2",
      project_name: "Martinez Bathroom Remodel",
      project_location: "456 River Road, Hoboken, NJ",
      permit_type: "Plumbing Permit",
      municipality: "Hudson County",
      status: "in_process",
      application_date: "2024-12-01",
      approval_date: null,
      permit_number: null,
      fees: 275,
    },
    {
      id: "demo-permit-3",
      project_id: "demo-project-3",
      project_name: "Thompson Basement Finishing",
      project_location: "789 Valley Road, Montclair, NJ",
      permit_type: "Electrical Permit",
      municipality: "Essex County",
      status: "approved",
      application_date: "2024-10-20",
      approval_date: "2024-11-15",
      permit_number: "EP-2024-5678",
      fees: 325,
    },
    {
      id: "demo-permit-4",
      project_id: "demo-project-4",
      project_name: "Chen Home Addition",
      project_location: "555 Maple Ave, Ridgewood, NJ",
      permit_type: "Building Permit",
      municipality: "Bergen County",
      status: "pending",
      application_date: "2024-12-12",
      approval_date: null,
      permit_number: null,
      fees: 850,
    },
    {
      id: "demo-permit-5",
      project_id: "demo-project-4",
      project_name: "Chen Home Addition",
      project_location: "555 Maple Ave, Ridgewood, NJ",
      permit_type: "Electrical Permit",
      municipality: "Bergen County",
      status: "in_process",
      application_date: "2024-12-08",
      approval_date: null,
      permit_number: null,
      fees: 425,
    },
    {
      id: "demo-permit-6",
      project_id: "demo-project-5",
      project_name: "Anderson Whole Home Renovation",
      project_location: "892 Summit Ave, Summit, NJ",
      permit_type: "Building Permit",
      municipality: "Union County",
      status: "approved",
      application_date: "2024-09-15",
      approval_date: "2024-10-20",
      permit_number: "BP-2024-9012",
      fees: 1250,
    },
    {
      id: "demo-permit-7",
      project_id: "demo-project-5",
      project_name: "Anderson Whole Home Renovation",
      project_location: "892 Summit Ave, Summit, NJ",
      permit_type: "HVAC Permit",
      municipality: "Union County",
      status: "in_process",
      application_date: "2024-11-28",
      approval_date: null,
      permit_number: null,
      fees: 375,
    },
    {
      id: "demo-permit-8",
      project_id: "demo-project-6",
      project_name: "Williams Deck Addition",
      project_location: "234 Pine Street, Morristown, NJ",
      permit_type: "Building Permit",
      municipality: "Morris County",
      status: "pending",
      application_date: "2024-12-15",
      approval_date: null,
      permit_number: null,
      fees: 350,
    },
  ],
});

export const getDemoSimplePMAppointments = () => [
  {
    id: "demo-appt-1",
    client: "Johnson Family",
    project: "Kitchen Renovation - Bergen County",
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    time: "10:00 AM",
    location: "123 Oak Street, Ridgewood, NJ",
    status: "confirmed",
    type: "Site Visit"
  },
  {
    id: "demo-appt-2",
    client: "Martinez Family",
    project: "Master Bathroom Remodel",
    date: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    time: "2:00 PM",
    location: "456 River Road, Hoboken, NJ",
    status: "pending",
    type: "Initial Consultation"
  },
  {
    id: "demo-appt-3",
    client: "Thompson Residence",
    project: "Basement Finishing",
    date: new Date(Date.now() + 259200000).toISOString().split('T')[0],
    time: "9:00 AM",
    location: "789 Valley Road, Montclair, NJ",
    status: "confirmed",
    type: "Progress Review"
  },
  {
    id: "demo-appt-4",
    client: "Chen Family",
    project: "Home Addition",
    date: new Date(Date.now() + 345600000).toISOString().split('T')[0],
    time: "11:30 AM",
    location: "555 Maple Ave, Ridgewood, NJ",
    status: "pending",
    type: "Pre-Construction Meeting"
  },
  {
    id: "demo-appt-5",
    client: "Anderson Family",
    project: "Whole Home Renovation",
    date: new Date(Date.now() + 432000000).toISOString().split('T')[0],
    time: "3:00 PM",
    location: "892 Summit Ave, Summit, NJ",
    status: "confirmed",
    type: "Final Walkthrough"
  },
];

export const getDemoStats = () => ({
  totalProjects: 12,
  activeProjects: 5,
  completedProjects: 7,
  totalRevenue: 485000,
  pendingBids: 8,
  wonBids: 15,
  teamMembers: 12,
  upcomingAppointments: 6,
  // For useContractorStats hook
  newProjects: 5,
  revenue: 485000,
  requestsForProposals: 8,
  successfulBids: 15,
});

export const getDemoProjects = () => [
  {
    id: "demo-proj-1",
    name: "Kitchen Renovation - Bergen County",
    client_name: "Johnson Family",
    status: "in_progress",
    amount: 47500,
    start_date: "2025-01-15",
    estimated_completion: "2025-03-20",
    progress: 65,
    project_type: "Kitchen Remodel",
    address: "123 Oak Street, Ridgewood, NJ",
  },
  {
    id: "demo-proj-2",
    name: "Master Bathroom Remodel - Hoboken",
    client_name: "Martinez Family",
    status: "planning",
    amount: 32000,
    start_date: "2025-02-01",
    estimated_completion: "2025-03-15",
    progress: 15,
    project_type: "Bathroom Remodel",
    address: "456 River Road, Hoboken, NJ",
  },
  {
    id: "demo-proj-3",
    name: "Basement Finishing - Montclair",
    client_name: "Thompson Residence",
    status: "in_progress",
    amount: 65000,
    start_date: "2025-01-02",
    estimated_completion: "2025-04-15",
    progress: 40,
    project_type: "Basement Finishing",
    address: "789 Valley Road, Montclair, NJ",
  },
  {
    id: "demo-proj-4",
    name: "Deck & Patio - Wayne",
    client_name: "Wilson Family",
    status: "completed",
    amount: 18500,
    start_date: "2024-11-01",
    estimated_completion: "2024-12-15",
    progress: 100,
    project_type: "Outdoor Living",
    address: "321 Pine Lane, Wayne, NJ",
  },
  {
    id: "demo-proj-5",
    name: "Home Addition - Ridgewood",
    client_name: "Chen Family",
    status: "pending",
    amount: 125000,
    start_date: "2025-03-01",
    estimated_completion: "2025-08-30",
    progress: 0,
    project_type: "Addition",
    address: "555 Maple Ave, Ridgewood, NJ",
  },
  {
    id: "demo-proj-6",
    name: "Whole Home Renovation - Summit",
    client_name: "Anderson Family",
    status: "in_progress",
    amount: 185000,
    start_date: "2024-12-01",
    estimated_completion: "2025-06-15",
    progress: 25,
    project_type: "Whole Home",
    address: "892 Summit Ave, Summit, NJ",
  },
  {
    id: "demo-proj-7",
    name: "Garage Conversion - Morristown",
    client_name: "Patel Residence",
    status: "completed",
    amount: 42000,
    start_date: "2024-10-01",
    estimated_completion: "2024-11-30",
    progress: 100,
    project_type: "Addition",
    address: "145 Madison Ave, Morristown, NJ",
  },
  {
    id: "demo-proj-8",
    name: "Pool House Build - Short Hills",
    client_name: "Williams Estate",
    status: "planning",
    amount: 95000,
    start_date: "2025-04-01",
    estimated_completion: "2025-07-30",
    progress: 5,
    project_type: "New Construction",
    address: "78 Old Short Hills Rd, Short Hills, NJ",
  },
  {
    id: "demo-proj-9",
    name: "Home Office Remodel - Livingston",
    client_name: "Roberts Family",
    status: "completed",
    amount: 28000,
    start_date: "2024-09-15",
    estimated_completion: "2024-10-30",
    progress: 100,
    project_type: "Interior Remodel",
    address: "234 Northfield Rd, Livingston, NJ",
  },
  {
    id: "demo-proj-10",
    name: "Mudroom Addition - Millburn",
    client_name: "Garcia Family",
    status: "in_progress",
    amount: 35000,
    start_date: "2025-01-10",
    estimated_completion: "2025-02-28",
    progress: 55,
    project_type: "Addition",
    address: "567 Main St, Millburn, NJ",
  },
];

export const getDemoExpenses = () => [
  {
    id: "demo-exp-1",
    description: "Kitchen cabinets - Johnson project",
    category: "Materials",
    amount: 4250,
    date: "2025-01-18",
    project_name: "Kitchen Renovation - Bergen County",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-2",
    description: "Plumbing supplies - Martinez bathroom",
    category: "Materials",
    amount: 890,
    date: "2025-01-20",
    project_name: "Master Bathroom Remodel - Hoboken",
    status: "pending",
    receipt_url: null,
  },
  {
    id: "demo-exp-3",
    description: "Electrical supplies - Thompson basement",
    category: "Materials",
    amount: 1200,
    date: "2025-01-22",
    project_name: "Basement Finishing - Montclair",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-4",
    description: "Fuel reimbursement - site visits",
    category: "Travel",
    amount: 185,
    date: "2025-01-23",
    project_name: "General",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-5",
    description: "Equipment rental - concrete mixer",
    category: "Equipment",
    amount: 650,
    date: "2025-01-19",
    project_name: "Basement Finishing - Montclair",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-6",
    description: "Subcontractor - plumbing work",
    category: "Labor",
    amount: 3500,
    date: "2025-01-21",
    project_name: "Master Bathroom Remodel - Hoboken",
    status: "pending",
    receipt_url: null,
  },
  {
    id: "demo-exp-7",
    description: "Permit fees - Bergen County",
    category: "Permits",
    amount: 450,
    date: "2025-01-10",
    project_name: "Kitchen Renovation - Bergen County",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-8",
    description: "Safety equipment - PPE",
    category: "Equipment",
    amount: 320,
    date: "2025-01-15",
    project_name: "General",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-9",
    description: "Tile and grout - Johnson kitchen",
    category: "Materials",
    amount: 1850,
    date: "2025-01-24",
    project_name: "Kitchen Renovation - Bergen County",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-10",
    description: "HVAC ductwork - Thompson basement",
    category: "Materials",
    amount: 2200,
    date: "2025-01-25",
    project_name: "Basement Finishing - Montclair",
    status: "pending",
    receipt_url: null,
  },
  {
    id: "demo-exp-11",
    description: "Insulation materials - Millburn",
    category: "Materials",
    amount: 950,
    date: "2025-01-26",
    project_name: "Mudroom Addition - Millburn",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-12",
    description: "Subcontractor - electrical",
    category: "Labor",
    amount: 2800,
    date: "2025-01-27",
    project_name: "Whole Home Renovation - Summit",
    status: "pending",
    receipt_url: null,
  },
  {
    id: "demo-exp-13",
    description: "Windows and doors - Summit project",
    category: "Materials",
    amount: 8500,
    date: "2025-01-28",
    project_name: "Whole Home Renovation - Summit",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-14",
    description: "Dumpster rental - debris removal",
    category: "Equipment",
    amount: 750,
    date: "2025-01-29",
    project_name: "Basement Finishing - Montclair",
    status: "approved",
    receipt_url: null,
  },
  {
    id: "demo-exp-15",
    description: "Flooring materials - hardwood",
    category: "Materials",
    amount: 4800,
    date: "2025-01-30",
    project_name: "Whole Home Renovation - Summit",
    status: "pending",
    receipt_url: null,
  },
];

export const getDemoScheduleEvents = () => [
  {
    id: "demo-event-1",
    title: "Site walkthrough - Chen Addition",
    start: new Date(Date.now() + 86400000).toISOString(),
    end: new Date(Date.now() + 86400000 + 3600000).toISOString(),
    type: "walkthrough",
    project_name: "Home Addition - Ridgewood",
    location: "555 Maple Ave, Ridgewood, NJ",
  },
  {
    id: "demo-event-2",
    title: "Client meeting - Johnson Kitchen",
    start: new Date(Date.now() + 172800000).toISOString(),
    end: new Date(Date.now() + 172800000 + 5400000).toISOString(),
    type: "meeting",
    project_name: "Kitchen Renovation - Bergen County",
    location: "123 Oak Street, Ridgewood, NJ",
  },
  {
    id: "demo-event-3",
    title: "Inspection - Thompson Basement",
    start: new Date(Date.now() + 259200000).toISOString(),
    end: new Date(Date.now() + 259200000 + 3600000).toISOString(),
    type: "inspection",
    project_name: "Basement Finishing - Montclair",
    location: "789 Valley Road, Montclair, NJ",
  },
  {
    id: "demo-event-4",
    title: "Material delivery - Hoboken",
    start: new Date(Date.now() + 345600000).toISOString(),
    end: new Date(Date.now() + 345600000 + 7200000).toISOString(),
    type: "delivery",
    project_name: "Master Bathroom Remodel - Hoboken",
    location: "456 River Road, Hoboken, NJ",
  },
  {
    id: "demo-event-5",
    title: "Permit pickup - Bergen County",
    start: new Date(Date.now() + 432000000).toISOString(),
    end: new Date(Date.now() + 432000000 + 3600000).toISOString(),
    type: "permit",
    project_name: "Kitchen Renovation - Bergen County",
    location: "Bergen County Building Department",
  },
  {
    id: "demo-event-6",
    title: "Final walkthrough - Wilson Deck",
    start: new Date(Date.now() + 518400000).toISOString(),
    end: new Date(Date.now() + 518400000 + 5400000).toISOString(),
    type: "walkthrough",
    project_name: "Deck & Patio - Wayne",
    location: "321 Pine Lane, Wayne, NJ",
  },
  {
    id: "demo-event-7",
    title: "Subcontractor coordination - Summit",
    start: new Date(Date.now() + 604800000).toISOString(),
    end: new Date(Date.now() + 604800000 + 7200000).toISOString(),
    type: "meeting",
    project_name: "Whole Home Renovation - Summit",
    location: "892 Summit Ave, Summit, NJ",
  },
  {
    id: "demo-event-8",
    title: "Framing inspection - Millburn",
    start: new Date(Date.now() + 691200000).toISOString(),
    end: new Date(Date.now() + 691200000 + 3600000).toISOString(),
    type: "inspection",
    project_name: "Mudroom Addition - Millburn",
    location: "567 Main St, Millburn, NJ",
  },
  {
    id: "demo-event-9",
    title: "Pool house site prep - Short Hills",
    start: new Date(Date.now() + 777600000).toISOString(),
    end: new Date(Date.now() + 777600000 + 14400000).toISOString(),
    type: "work",
    project_name: "Pool House Build - Short Hills",
    location: "78 Old Short Hills Rd, Short Hills, NJ",
  },
  {
    id: "demo-event-10",
    title: "Cabinet installation - Johnson",
    start: new Date(Date.now() + 864000000).toISOString(),
    end: new Date(Date.now() + 864000000 + 28800000).toISOString(),
    type: "work",
    project_name: "Kitchen Renovation - Bergen County",
    location: "123 Oak Street, Ridgewood, NJ",
  },
];

export const getDemoMessages = () => [
  {
    id: "demo-msg-1",
    sender_name: "Sarah Johnson",
    subject: "Kitchen tile selection question",
    preview: "Hi, I wanted to ask about the backsplash tile options we discussed...",
    message: "Hi, I wanted to ask about the backsplash tile options we discussed. Can we schedule a call?",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 3600000).toISOString(),
    read: false,
    is_read: false,
    project_name: "Kitchen Renovation - Bergen County",
    project_id: "demo-proj-1",
  },
  {
    id: "demo-msg-2",
    sender_name: "SmartReno Team",
    subject: "New RFP available in your area",
    preview: "A new bathroom renovation project in Paramus is looking for bids...",
    message: "A new bathroom renovation project in Paramus is looking for bids. Check it out!",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    read: false,
    is_read: false,
    project_name: null,
    project_id: null,
  },
  {
    id: "demo-msg-3",
    sender_name: "Mike Chen",
    subject: "Addition project timeline",
    preview: "Thank you for the detailed proposal. We have a few questions about...",
    message: "Thank you for the detailed proposal. We have a few questions about the timeline.",
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    read: true,
    is_read: true,
    project_name: "Home Addition - Ridgewood",
    project_id: "demo-proj-5",
  },
  {
    id: "demo-msg-4",
    sender_name: "Bergen County Permits",
    subject: "Permit approved",
    preview: "Your permit application #BC-2025-0123 has been approved...",
    message: "Your permit application #BC-2025-0123 has been approved. Please pick it up.",
    timestamp: new Date(Date.now() - 259200000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
    read: true,
    is_read: true,
    project_name: "Kitchen Renovation - Bergen County",
    project_id: "demo-proj-1",
  },
  {
    id: "demo-msg-5",
    sender_name: "Tom Anderson",
    subject: "Change order approval",
    preview: "We've reviewed the change order for the additional electrical work...",
    message: "We've reviewed the change order for the additional electrical work and approve the changes.",
    timestamp: new Date(Date.now() - 345600000).toISOString(),
    created_at: new Date(Date.now() - 345600000).toISOString(),
    read: false,
    is_read: false,
    project_name: "Whole Home Renovation - Summit",
    project_id: "demo-proj-6",
  },
  {
    id: "demo-msg-6",
    sender_name: "Maria Garcia (Construction Agent)",
    subject: "Bid submission received",
    preview: "Your bid for the Paramus kitchen project has been received and is under review...",
    message: "Your bid for the Paramus kitchen project has been received and is under review.",
    timestamp: new Date(Date.now() - 432000000).toISOString(),
    created_at: new Date(Date.now() - 432000000).toISOString(),
    read: true,
    is_read: true,
    project_name: null,
    project_id: null,
  },
  {
    id: "demo-msg-7",
    sender_name: "Linda Thompson",
    subject: "Basement progress update request",
    preview: "Could you send us some photos of the current progress on the basement?",
    message: "Could you send us some photos of the current progress on the basement finishing?",
    timestamp: new Date(Date.now() - 518400000).toISOString(),
    created_at: new Date(Date.now() - 518400000).toISOString(),
    read: true,
    is_read: true,
    project_name: "Basement Finishing - Montclair",
    project_id: "demo-proj-3",
  },
  {
    id: "demo-msg-8",
    sender_name: "Home Depot Pro Desk",
    subject: "Order ready for pickup",
    preview: "Your order #HD2025-4567 for lumber and supplies is ready for pickup...",
    message: "Your order #HD2025-4567 for lumber and supplies is ready for pickup at our Wayne location.",
    timestamp: new Date(Date.now() - 604800000).toISOString(),
    created_at: new Date(Date.now() - 604800000).toISOString(),
    read: true,
    is_read: true,
    project_name: "Mudroom Addition - Millburn",
    project_id: "demo-proj-10",
  },
];

export const getDemoTeamMembers = () => [
  {
    id: "demo-team-1",
    name: "John Smith",
    role: "Project Manager",
    email: "john@democonstruction.com",
    phone: "(555) 123-4567",
    status: "active",
    projects_assigned: 3,
  },
  {
    id: "demo-team-2",
    name: "Maria Garcia",
    role: "Construction Agent",
    email: "maria@democonstruction.com",
    phone: "(555) 234-5678",
    status: "active",
    projects_assigned: 2,
  },
  {
    id: "demo-team-3",
    name: "Robert Lee",
    role: "Field Supervisor",
    email: "robert@democonstruction.com",
    phone: "(555) 345-6789",
    status: "active",
    projects_assigned: 4,
  },
  {
    id: "demo-team-4",
    name: "Emily Davis",
    role: "Office Manager",
    email: "emily@democonstruction.com",
    phone: "(555) 456-7890",
    status: "active",
    projects_assigned: 0,
  },
  {
    id: "demo-team-5",
    name: "Carlos Rodriguez",
    role: "Foreman",
    email: "carlos@democonstruction.com",
    phone: "(555) 567-8901",
    status: "active",
    projects_assigned: 2,
  },
  {
    id: "demo-team-6",
    name: "James Wilson",
    role: "Lead Carpenter",
    email: "james@democonstruction.com",
    phone: "(555) 678-9012",
    status: "active",
    projects_assigned: 3,
  },
  {
    id: "demo-team-7",
    name: "Sarah Chen",
    role: "Project Coordinator",
    email: "sarah@democonstruction.com",
    phone: "(555) 789-0123",
    status: "active",
    projects_assigned: 4,
  },
  {
    id: "demo-team-8",
    name: "Michael Brown",
    role: "Site Safety Manager",
    email: "michael@democonstruction.com",
    phone: "(555) 890-1234",
    status: "active",
    projects_assigned: 5,
  },
];

export const getDemoBidOpportunities = () => [
  {
    id: "demo-rfp-1",
    title: "Full Kitchen Renovation - Paramus",
    location: "Paramus, NJ",
    estimated_budget: 55000,
    deadline: new Date(Date.now() + 604800000).toISOString(),
    bid_deadline: new Date(Date.now() + 604800000).toISOString(),
    project_type: "Kitchen Remodel",
    description: "Complete kitchen renovation including cabinets, countertops, appliances, and flooring.",
    status: "open",
  },
  {
    id: "demo-rfp-2",
    title: "Bathroom Addition - Hackensack",
    location: "Hackensack, NJ",
    estimated_budget: 38000,
    deadline: new Date(Date.now() + 432000000).toISOString(),
    bid_deadline: new Date(Date.now() + 432000000).toISOString(),
    project_type: "Bathroom Addition",
    description: "Adding a full bathroom to existing home, including all plumbing and electrical work.",
    status: "open",
  },
  {
    id: "demo-rfp-3",
    title: "Deck Construction - Tenafly",
    location: "Tenafly, NJ",
    estimated_budget: 25000,
    deadline: new Date(Date.now() + 864000000).toISOString(),
    bid_deadline: new Date(Date.now() + 864000000).toISOString(),
    project_type: "Outdoor Living",
    description: "New composite deck with built-in seating and lighting.",
    status: "open",
  },
  {
    id: "demo-rfp-4",
    title: "Basement Waterproofing - Fort Lee",
    location: "Fort Lee, NJ",
    estimated_budget: 15000,
    deadline: new Date(Date.now() + 259200000).toISOString(),
    bid_deadline: new Date(Date.now() + 259200000).toISOString(),
    project_type: "Basement",
    description: "Complete basement waterproofing including sump pump installation.",
    status: "open",
  },
  {
    id: "demo-rfp-5",
    title: "Master Suite Renovation - Englewood",
    location: "Englewood, NJ",
    estimated_budget: 75000,
    deadline: new Date(Date.now() + 1209600000).toISOString(),
    bid_deadline: new Date(Date.now() + 1209600000).toISOString(),
    project_type: "Whole Home",
    description: "Master bedroom and bathroom renovation with walk-in closet addition.",
    status: "open",
  },
  {
    id: "demo-rfp-6",
    title: "Garage Conversion - Clifton",
    location: "Clifton, NJ",
    estimated_budget: 45000,
    deadline: new Date(Date.now() + 950400000).toISOString(),
    bid_deadline: new Date(Date.now() + 950400000).toISOString(),
    project_type: "Addition",
    description: "Convert 2-car garage into living space with HVAC and egress window.",
    status: "open",
  },
  {
    id: "demo-rfp-7",
    title: "Sunroom Addition - Glen Rock",
    location: "Glen Rock, NJ",
    estimated_budget: 60000,
    deadline: new Date(Date.now() + 1382400000).toISOString(),
    bid_deadline: new Date(Date.now() + 1382400000).toISOString(),
    project_type: "Addition",
    description: "Three-season sunroom addition with skylights and sliding doors.",
    status: "open",
  },
  {
    id: "demo-rfp-8",
    title: "Historic Home Restoration - Montclair",
    location: "Montclair, NJ",
    estimated_budget: 120000,
    deadline: new Date(Date.now() + 1728000000).toISOString(),
    bid_deadline: new Date(Date.now() + 1728000000).toISOString(),
    project_type: "Restoration",
    description: "Full exterior restoration of 1920s colonial including windows, siding, and trim.",
    status: "open",
  },
];

export const getDemoActionItems = () => [
  {
    id: "demo-action-1",
    type: "bid" as const,
    title: "Submit your bid for Full Kitchen Renovation - Paramus",
    subtitle: "Paramus, NJ",
    priority: "high" as const,
    buttonText: "Submit proposal",
    relatedId: "demo-rfp-1",
  },
  {
    id: "demo-action-2",
    type: "review" as const,
    title: "Review estimator notes for Bathroom Addition",
    subtitle: "Hackensack project",
    priority: "medium" as const,
    buttonText: "View Estimate",
    relatedId: "demo-rfp-2",
  },
  {
    id: "demo-action-3",
    type: "message" as const,
    title: "Sarah Johnson sent a message",
    subtitle: "Kitchen tile selection question...",
    priority: "medium" as const,
    buttonText: "View Message",
    relatedId: "demo-proj-1",
  },
  {
    id: "demo-action-4",
    type: "bid" as const,
    title: "Submit your bid for Deck Construction - Tenafly",
    subtitle: "Tenafly, NJ",
    priority: "medium" as const,
    buttonText: "Submit proposal",
    relatedId: "demo-rfp-3",
  },
];

export const getDemoNotifications = () => [
  {
    id: "demo-notif-1",
    title: "New RFP Available",
    message: "A new kitchen renovation project in Paramus matches your profile.",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: false,
    type: "rfp",
  },
  {
    id: "demo-notif-2",
    title: "Payment Received",
    message: "Payment of $15,000 received for Deck & Patio project.",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: false,
    type: "payment",
  },
  {
    id: "demo-notif-3",
    title: "Bid Accepted",
    message: "Your bid for the Chen Addition project has been accepted!",
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    read: true,
    type: "bid",
  },
];

export const getDemoExpenseReports = () => [
  {
    id: "demo-report-1",
    period: "January 2025",
    total_expenses: 11445,
    total_approved: 7055,
    total_pending: 4390,
    expense_count: 8,
    categories: {
      Materials: 6340,
      Travel: 185,
      Equipment: 970,
      Labor: 3500,
      Permits: 450,
    },
  },
  {
    id: "demo-report-2",
    period: "December 2024",
    total_expenses: 18250,
    total_approved: 18250,
    total_pending: 0,
    expense_count: 12,
    categories: {
      Materials: 12500,
      Travel: 450,
      Equipment: 2800,
      Labor: 2000,
      Permits: 500,
    },
  },
];

// Demo invoices
export const getDemoInvoices = () => [
  {
    id: "demo-inv-1",
    invoice_number: "INV-2025-001",
    project_name: "Kitchen Renovation - Bergen County",
    project_id: "demo-proj-1",
    client_name: "Johnson Family",
    amount: 14250,
    status: "paid",
    due_date: "2025-01-15",
    paid_date: "2025-01-12",
    created_at: "2025-01-01",
  },
  {
    id: "demo-inv-2",
    invoice_number: "INV-2025-002",
    project_name: "Basement Finishing - Montclair",
    project_id: "demo-proj-3",
    client_name: "Thompson Residence",
    amount: 19500,
    status: "pending",
    due_date: "2025-02-01",
    paid_date: null,
    created_at: "2025-01-18",
  },
  {
    id: "demo-inv-3",
    invoice_number: "INV-2025-003",
    project_name: "Deck & Patio - Wayne",
    project_id: "demo-proj-4",
    client_name: "Wilson Family",
    amount: 18500,
    status: "paid",
    due_date: "2024-12-20",
    paid_date: "2024-12-18",
    created_at: "2024-12-05",
  },
  {
    id: "demo-inv-4",
    invoice_number: "INV-2025-004",
    project_name: "Whole Home Renovation - Summit",
    project_id: "demo-proj-6",
    client_name: "Anderson Family",
    amount: 37000,
    status: "overdue",
    due_date: "2025-01-25",
    paid_date: null,
    created_at: "2025-01-10",
  },
  {
    id: "demo-inv-5",
    invoice_number: "INV-2025-005",
    project_name: "Master Bathroom Remodel - Hoboken",
    project_id: "demo-proj-2",
    client_name: "Martinez Family",
    amount: 8000,
    status: "pending",
    due_date: "2025-02-15",
    paid_date: null,
    created_at: "2025-01-28",
  },
  {
    id: "demo-inv-6",
    invoice_number: "INV-2024-089",
    project_name: "Home Office Remodel - Livingston",
    project_id: "demo-proj-9",
    client_name: "Roberts Family",
    amount: 28000,
    status: "paid",
    due_date: "2024-11-15",
    paid_date: "2024-11-10",
    created_at: "2024-10-30",
  },
];

// Demo change orders
export const getDemoChangeOrders = () => [
  {
    id: "demo-co-1",
    change_order_number: "CO-2025-001",
    project_name: "Kitchen Renovation - Bergen County",
    project_id: "demo-proj-1",
    description: "Upgrade to quartz countertops from laminate",
    change_amount: 3500,
    status: "approved",
    created_at: "2025-01-20",
    approved_at: "2025-01-22",
  },
  {
    id: "demo-co-2",
    change_order_number: "CO-2025-002",
    project_name: "Basement Finishing - Montclair",
    project_id: "demo-proj-3",
    description: "Add egress window per code requirement",
    change_amount: 4200,
    status: "pending",
    created_at: "2025-01-25",
    approved_at: null,
  },
  {
    id: "demo-co-3",
    change_order_number: "CO-2025-003",
    project_name: "Whole Home Renovation - Summit",
    project_id: "demo-proj-6",
    description: "Additional electrical panel upgrade",
    change_amount: 2800,
    status: "approved",
    created_at: "2025-01-15",
    approved_at: "2025-01-18",
  },
  {
    id: "demo-co-4",
    change_order_number: "CO-2025-004",
    project_name: "Master Bathroom Remodel - Hoboken",
    project_id: "demo-proj-2",
    description: "Heated floor tile installation",
    change_amount: 1800,
    status: "pending",
    created_at: "2025-01-28",
    approved_at: null,
  },
];

// Demo contracts
export const getDemoContracts = () => [
  {
    id: "demo-contract-1",
    contract_number: "C-2025-001",
    project_name: "Kitchen Renovation - Bergen County",
    project_id: "demo-proj-1",
    client_name: "Johnson Family",
    contract_value: 47500,
    status: "signed",
    signed_at: "2025-01-10",
    created_at: "2025-01-05",
  },
  {
    id: "demo-contract-2",
    contract_number: "C-2025-002",
    project_name: "Master Bathroom Remodel - Hoboken",
    project_id: "demo-proj-2",
    client_name: "Martinez Family",
    contract_value: 32000,
    status: "signed",
    signed_at: "2025-01-28",
    created_at: "2025-01-20",
  },
  {
    id: "demo-contract-3",
    contract_number: "C-2025-003",
    project_name: "Home Addition - Ridgewood",
    project_id: "demo-proj-5",
    client_name: "Chen Family",
    contract_value: 125000,
    status: "pending",
    signed_at: null,
    created_at: "2025-01-30",
  },
  {
    id: "demo-contract-4",
    contract_number: "C-2024-045",
    project_name: "Whole Home Renovation - Summit",
    project_id: "demo-proj-6",
    client_name: "Anderson Family",
    contract_value: 185000,
    status: "signed",
    signed_at: "2024-11-25",
    created_at: "2024-11-15",
  },
];

// Demo calendar events for full calendar view
export const getDemoCalendarEvents = () => [
  {
    id: "demo-cal-1",
    title: "Site walkthrough - Chen Addition",
    event_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    event_time: "09:00",
    description: "Initial walkthrough with homeowners",
    location: "555 Maple Ave, Ridgewood, NJ",
  },
  {
    id: "demo-cal-2",
    title: "Client meeting - Johnson Kitchen",
    event_date: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    event_time: "14:00",
    description: "Review progress and tile selections",
    location: "123 Oak Street, Ridgewood, NJ",
  },
  {
    id: "demo-cal-3",
    title: "Inspection - Thompson Basement",
    event_date: new Date(Date.now() + 259200000).toISOString().split('T')[0],
    event_time: "10:00",
    description: "Electrical rough-in inspection",
    location: "789 Valley Road, Montclair, NJ",
  },
  {
    id: "demo-cal-4",
    title: "Material delivery - Hoboken",
    event_date: new Date(Date.now() + 345600000).toISOString().split('T')[0],
    event_time: "08:00",
    description: "Tile and fixtures delivery",
    location: "456 River Road, Hoboken, NJ",
  },
  {
    id: "demo-cal-5",
    title: "Permit pickup - Bergen County",
    event_date: new Date(Date.now() + 432000000).toISOString().split('T')[0],
    event_time: "11:00",
    description: "Pick up approved permit",
    location: "Bergen County Building Department",
  },
];

// Demo tasks for calendar
export const getDemoTasks = () => [
  {
    id: "demo-task-1",
    task_title: "Order cabinet hardware - Johnson",
    due_date: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    description: "Order handles and pulls for kitchen cabinets",
    location: null,
    priority: "high",
    status: "pending",
  },
  {
    id: "demo-task-2",
    task_title: "Schedule HVAC sub - Thompson",
    due_date: new Date(Date.now() + 345600000).toISOString().split('T')[0],
    description: "Coordinate HVAC ductwork installation",
    location: "789 Valley Road, Montclair, NJ",
    priority: "medium",
    status: "pending",
  },
  {
    id: "demo-task-3",
    task_title: "Submit change order - Anderson",
    due_date: new Date(Date.now() + 518400000).toISOString().split('T')[0],
    description: "Submit CO for electrical panel upgrade",
    location: null,
    priority: "high",
    status: "in_progress",
  },
];

// Helper function to get active projects for dashboard hooks
export const getDemoActiveProjects = () => {
  const projects = getDemoProjects();
  return projects
    .filter(p => ['planning', 'in_progress', 'pending'].includes(p.status))
    .map(p => ({
      id: p.id,
      title: p.name,
      location: p.address,
      value: `$${(p.amount / 1000).toFixed(0)}k est.`,
      dueDate: p.estimated_completion ? `Due ${new Date(p.estimated_completion).toLocaleDateString()}` : 'No deadline',
      status: p.status,
    }));
};

// Helper function for dashboard schedule
export const getDemoTodaySchedule = () => {
  return getDemoScheduleEvents().slice(0, 5).map(event => ({
    id: event.id,
    time: new Date(event.start).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }),
    title: event.title,
    location: event.location || 'Location TBD',
    projectId: event.id,
  }));
};

// Helper function for dashboard messages
export const getDemoRecentMessages = () => {
  return getDemoMessages().slice(0, 5).map(msg => {
    const timeDiff = Date.now() - new Date(msg.timestamp).getTime();
    const hoursAgo = Math.floor(timeDiff / (1000 * 60 * 60));
    return {
      id: msg.id,
      sender: msg.sender_name,
      preview: msg.preview.substring(0, 30) + '...',
      time: hoursAgo < 1 ? 'Just now' : `${hoursAgo}h ago`,
      projectId: msg.project_id || undefined,
    };
  });
};

// Demo vendors
export const getDemoVendors = () => [
  {
    id: "demo-vendor-1",
    company_name: "ABC Plumbing Supply",
    contact_name: "Mike Johnson",
    email: "mike@abcplumbing.com",
    phone: "(555) 111-2222",
    address: "123 Industrial Blvd, Newark, NJ",
    categories: ["Plumbing", "Fixtures"],
    rating: 5,
    payment_terms: "Net 30",
    status: "active",
    notes: "Preferred plumbing supplier",
    website: "www.abcplumbing.com",
    tax_id: "12-3456789",
    created_at: "2024-01-15",
    updated_at: "2025-01-10",
  },
  {
    id: "demo-vendor-2",
    company_name: "Bergen Electric Wholesale",
    contact_name: "Susan Lee",
    email: "susan@bergenelectric.com",
    phone: "(555) 222-3333",
    address: "456 Commerce Way, Hackensack, NJ",
    categories: ["Electrical", "Lighting"],
    rating: 4,
    payment_terms: "Net 15",
    status: "active",
    notes: "Fast delivery, good prices",
    website: "www.bergenelectric.com",
    tax_id: "23-4567890",
    created_at: "2024-02-20",
    updated_at: "2025-01-08",
  },
  {
    id: "demo-vendor-3",
    company_name: "Premium Lumber Co",
    contact_name: "Tom Brown",
    email: "tom@premiumlumber.com",
    phone: "(555) 333-4444",
    address: "789 Wood Lane, Paramus, NJ",
    categories: ["Lumber", "Building Materials"],
    rating: 5,
    payment_terms: "Net 30",
    status: "active",
    notes: "Quality hardwood specialist",
    website: "www.premiumlumber.com",
    tax_id: "34-5678901",
    created_at: "2024-03-10",
    updated_at: "2025-01-15",
  },
  {
    id: "demo-vendor-4",
    company_name: "NJ HVAC Systems",
    contact_name: "David Wilson",
    email: "david@njhvac.com",
    phone: "(555) 444-5555",
    address: "321 Climate Dr, Wayne, NJ",
    categories: ["HVAC", "Equipment"],
    rating: 4,
    payment_terms: "Net 45",
    status: "active",
    notes: "Carrier authorized dealer",
    website: "www.njhvac.com",
    tax_id: "45-6789012",
    created_at: "2024-04-05",
    updated_at: "2025-01-12",
  },
  {
    id: "demo-vendor-5",
    company_name: "Tile Masters NJ",
    contact_name: "Maria Santos",
    email: "maria@tilemasters.com",
    phone: "(555) 555-6666",
    address: "555 Ceramic Ave, Fort Lee, NJ",
    categories: ["Tile", "Flooring"],
    rating: 5,
    payment_terms: "Net 30",
    status: "active",
    notes: "Wide selection, custom orders",
    website: "www.tilemastersny.com",
    tax_id: "56-7890123",
    created_at: "2024-05-15",
    updated_at: "2025-01-05",
  },
  {
    id: "demo-vendor-6",
    company_name: "Kitchen Cabinet Depot",
    contact_name: "Robert Chen",
    email: "robert@cabinetdepot.com",
    phone: "(555) 666-7777",
    address: "777 Cabinet Way, Englewood, NJ",
    categories: ["Cabinets", "Countertops"],
    rating: 4,
    payment_terms: "50% deposit",
    status: "active",
    notes: "Custom cabinetry available",
    website: "www.kitchencabinetdepot.com",
    tax_id: "67-8901234",
    created_at: "2024-06-20",
    updated_at: "2025-01-18",
  },
  {
    id: "demo-vendor-7",
    company_name: "SafeGuard Insurance",
    contact_name: "Jennifer Adams",
    email: "jadams@safeguard.com",
    phone: "(555) 777-8888",
    address: "888 Insurance Plaza, Morristown, NJ",
    categories: ["Insurance", "Bonds"],
    rating: 4,
    payment_terms: "Monthly",
    status: "active",
    notes: "Contractor liability specialist",
    website: "www.safeguardins.com",
    tax_id: "78-9012345",
    created_at: "2024-07-01",
    updated_at: "2025-01-02",
  },
  {
    id: "demo-vendor-8",
    company_name: "Concrete Solutions LLC",
    contact_name: "James Murphy",
    email: "james@concretesolutions.com",
    phone: "(555) 888-9999",
    address: "999 Foundation Rd, Summit, NJ",
    categories: ["Concrete", "Masonry"],
    rating: 3,
    payment_terms: "Net 15",
    status: "inactive",
    notes: "Good for small jobs",
    website: "www.concretesolutions.com",
    tax_id: "89-0123456",
    created_at: "2024-08-10",
    updated_at: "2024-12-01",
  },
];

// Demo documents
export const getDemoDocuments = () => [
  {
    id: "demo-doc-1",
    file_name: "Building_Permit_Johnson_Kitchen.pdf",
    file_path: "demo/permits/johnson_kitchen_permit.pdf",
    file_type: "application/pdf",
    file_size: 245000,
    document_type: "permits",
    description: "Bergen County building permit for kitchen renovation",
    project_id: "demo-proj-1",
    created_at: "2025-01-10",
  },
  {
    id: "demo-doc-2",
    file_name: "Contract_Thompson_Basement.pdf",
    file_path: "demo/contracts/thompson_basement_contract.pdf",
    file_type: "application/pdf",
    file_size: 380000,
    document_type: "contracts",
    description: "Signed contract for basement finishing project",
    project_id: "demo-proj-3",
    created_at: "2025-01-02",
  },
  {
    id: "demo-doc-3",
    file_name: "Change_Order_001_Anderson.pdf",
    file_path: "demo/change_orders/anderson_co_001.pdf",
    file_type: "application/pdf",
    file_size: 125000,
    document_type: "change_orders",
    description: "Electrical panel upgrade change order",
    project_id: "demo-proj-6",
    created_at: "2025-01-15",
  },
  {
    id: "demo-doc-4",
    file_name: "Insurance_Certificate_2025.pdf",
    file_path: "demo/insurance/insurance_cert_2025.pdf",
    file_type: "application/pdf",
    file_size: 175000,
    document_type: "insurance",
    description: "General liability insurance certificate",
    project_id: "demo-proj-1",
    created_at: "2025-01-01",
  },
  {
    id: "demo-doc-5",
    file_name: "Inspection_Report_Electrical.pdf",
    file_path: "demo/inspections/thompson_electrical_inspection.pdf",
    file_type: "application/pdf",
    file_size: 290000,
    document_type: "inspections",
    description: "Electrical rough-in inspection report - passed",
    project_id: "demo-proj-3",
    created_at: "2025-01-22",
  },
  {
    id: "demo-doc-6",
    file_name: "Plumbing_Permit_Martinez.pdf",
    file_path: "demo/permits/martinez_plumbing_permit.pdf",
    file_type: "application/pdf",
    file_size: 210000,
    document_type: "permits",
    description: "Plumbing permit for bathroom remodel",
    project_id: "demo-proj-2",
    created_at: "2025-01-28",
  },
  {
    id: "demo-doc-7",
    file_name: "Contract_Chen_Addition.pdf",
    file_path: "demo/contracts/chen_addition_contract.pdf",
    file_type: "application/pdf",
    file_size: 425000,
    document_type: "contracts",
    description: "Home addition project contract",
    project_id: "demo-proj-5",
    created_at: "2025-01-30",
  },
  {
    id: "demo-doc-8",
    file_name: "Workers_Comp_Certificate.pdf",
    file_path: "demo/insurance/workers_comp_2025.pdf",
    file_type: "application/pdf",
    file_size: 165000,
    document_type: "insurance",
    description: "Workers compensation insurance certificate",
    project_id: "demo-proj-1",
    created_at: "2025-01-01",
  },
  {
    id: "demo-doc-9",
    file_name: "Framing_Inspection_Millburn.pdf",
    file_path: "demo/inspections/millburn_framing_inspection.pdf",
    file_type: "application/pdf",
    file_size: 315000,
    document_type: "inspections",
    description: "Framing inspection report for mudroom addition",
    project_id: "demo-proj-10",
    created_at: "2025-01-25",
  },
  {
    id: "demo-doc-10",
    file_name: "Change_Order_002_Johnson.pdf",
    file_path: "demo/change_orders/johnson_co_002.pdf",
    file_type: "application/pdf",
    file_size: 135000,
    document_type: "change_orders",
    description: "Countertop upgrade to quartz",
    project_id: "demo-proj-1",
    created_at: "2025-01-20",
  },
];

// Demo estimates
export const getDemoEstimates = () => [
  {
    id: "demo-est-1",
    estimate_number: "EST-2025-001",
    client_name: "Johnson Family",
    project_name: "Kitchen Renovation",
    amount: 47500,
    status: "accepted",
    created_at: "2024-12-15",
    valid_until: "2025-01-15",
  },
  {
    id: "demo-est-2",
    estimate_number: "EST-2025-002",
    client_name: "Martinez Family",
    project_name: "Master Bathroom Remodel",
    amount: 32000,
    status: "accepted",
    created_at: "2025-01-10",
    valid_until: "2025-02-10",
  },
  {
    id: "demo-est-3",
    estimate_number: "EST-2025-003",
    client_name: "Chen Family",
    project_name: "Home Addition",
    amount: 125000,
    status: "sent",
    created_at: "2025-01-25",
    valid_until: "2025-02-25",
  },
  {
    id: "demo-est-4",
    estimate_number: "EST-2025-004",
    client_name: "Williams Estate",
    project_name: "Pool House Construction",
    amount: 95000,
    status: "draft",
    created_at: "2025-01-28",
    valid_until: "2025-02-28",
  },
  {
    id: "demo-est-5",
    estimate_number: "EST-2025-005",
    client_name: "Patel Family",
    project_name: "Basement Finishing",
    amount: 58000,
    status: "rejected",
    created_at: "2025-01-05",
    valid_until: "2025-02-05",
  },
  {
    id: "demo-est-6",
    estimate_number: "EST-2025-006",
    client_name: "Garcia Residence",
    project_name: "Mudroom Addition",
    amount: 35000,
    status: "accepted",
    created_at: "2024-12-20",
    valid_until: "2025-01-20",
  },
];

// Demo bid submissions for ContractorBidRoom - use getDemoBidOpportunities from above

// Demo bid submissions for ContractorBidRoom
export const getDemoBidSubmissions = () => [
  {
    id: "demo-sub-1",
    bid_opportunity_id: "demo-opp-old-1",
    bid_amount: 48500,
    estimated_timeline: "8-10 weeks",
    proposal_text: "Comprehensive kitchen renovation including custom cabinetry and premium appliances.",
    status: "under_review",
    submitted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    attachments: [],
    bid_opportunities: {
      id: "demo-opp-old-1",
      title: "Kitchen Remodel - Fort Lee",
      description: "Modern kitchen renovation project",
      project_type: "Kitchen Remodel",
      location: "Fort Lee, NJ",
      estimated_budget: 50000,
    },
  },
  {
    id: "demo-sub-2",
    bid_opportunity_id: "demo-opp-old-2",
    bid_amount: 125000,
    estimated_timeline: "4-5 months",
    proposal_text: "Full home addition with architectural plans and permit coordination included.",
    status: "accepted",
    submitted_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    attachments: ["portfolio_additions.pdf"],
    bid_opportunities: {
      id: "demo-opp-old-2",
      title: "Home Addition - Ridgewood",
      description: "Two-story addition for growing family",
      project_type: "Addition",
      location: "Ridgewood, NJ",
      estimated_budget: 130000,
    },
  },
  {
    id: "demo-sub-3",
    bid_opportunity_id: "demo-opp-old-3",
    bid_amount: 28000,
    estimated_timeline: "4-6 weeks",
    proposal_text: "Premium bathroom remodel with luxury fixtures and custom tilework.",
    status: "submitted",
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    attachments: [],
    bid_opportunities: {
      id: "demo-opp-old-3",
      title: "Bathroom Renovation - Hackensack",
      description: "Master bathroom upgrade",
      project_type: "Bathroom Remodel",
      location: "Hackensack, NJ",
      estimated_budget: 30000,
    },
  },
];

// Demo leads for InsideSales & OutsideSales
export const getDemoLeads = () => [
  {
    id: "demo-lead-1",
    name: "Robert Anderson",
    email: "robert.anderson@email.com",
    phone: "(201) 555-0123",
    status: "new",
    location: "123 Main St, Ridgewood, NJ",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    project_type: "Kitchen Remodel",
    last_contact: "",
    notes: "Interested in full kitchen renovation. Budget around $45K.",
    internal_notes: "Interested in full kitchen renovation. Budget around $45K.",
  },
  {
    id: "demo-lead-2",
    name: "Jennifer Martinez",
    email: "jmartinez@email.com",
    phone: "(201) 555-0456",
    status: "contacted",
    location: "456 Oak Ave, Paramus, NJ",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    project_type: "Bathroom Remodel",
    last_contact: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: "Wants to modernize master bathroom. Prefers walk-in shower.",
    internal_notes: "Wants to modernize master bathroom. Prefers walk-in shower.",
  },
  {
    id: "demo-lead-3",
    name: "Michael Chen",
    email: "mchen@email.com",
    phone: "(973) 555-0789",
    status: "qualified",
    location: "789 Elm St, Montclair, NJ",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    project_type: "Home Addition",
    last_contact: new Date(Date.now() - 3 * 86400000).toISOString(),
    notes: "Adding second floor. Has architectural plans ready.",
    internal_notes: "Adding second floor. Has architectural plans ready.",
  },
  {
    id: "demo-lead-4",
    name: "Sarah Thompson",
    email: "sthompson@email.com",
    phone: "(201) 555-0321",
    status: "new_lead",
    location: "321 Pine Rd, Englewood, NJ",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    project_type: "Basement Finishing",
    last_contact: "",
    notes: "Just submitted inquiry through website.",
    internal_notes: "Just submitted inquiry through website.",
  },
  {
    id: "demo-lead-5",
    name: "David Wilson",
    email: "dwilson@email.com",
    phone: "(201) 555-0654",
    status: "call_24h",
    location: "654 Maple Dr, Fort Lee, NJ",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    project_type: "Deck & Patio",
    last_contact: "",
    notes: "URGENT: Called back twice, needs callback within 24 hours.",
    internal_notes: "URGENT: Called back twice, needs callback within 24 hours.",
  },
  {
    id: "demo-lead-6",
    name: "Lisa Brown",
    email: "lbrown@email.com",
    phone: "(973) 555-0987",
    status: "walkthrough_scheduled",
    location: "987 Cedar Lane, Summit, NJ",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    project_type: "Whole Home Renovation",
    last_contact: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: "Walkthrough scheduled for next week. Major renovation project.",
    internal_notes: "Walkthrough scheduled for next week. Major renovation project.",
  },
];

// Demo call logs for InsideSales
export const getDemoCallLogs = () => [
  {
    id: "demo-call-1",
    lead_id: "demo-lead-2",
    from_number: "(201) 555-0456",
    duration_seconds: 420,
    disposition: "completed",
    notes: "Discussed bathroom renovation options. Client interested in premium fixtures.",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    call_status: "completed",
    lead: { name: "Jennifer Martinez" },
  },
  {
    id: "demo-call-2",
    lead_id: "demo-lead-3",
    from_number: "(973) 555-0789",
    duration_seconds: 900,
    disposition: "completed",
    notes: "Detailed discussion about home addition. Client has plans from architect.",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    call_status: "completed",
    lead: { name: "Michael Chen" },
  },
  {
    id: "demo-call-3",
    lead_id: "demo-lead-5",
    from_number: "(201) 555-0654",
    duration_seconds: 0,
    disposition: "no_answer",
    notes: "No answer, left voicemail about deck project inquiry.",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    call_status: "no_answer",
    lead: { name: "David Wilson" },
  },
  {
    id: "demo-call-4",
    lead_id: "demo-lead-6",
    from_number: "(973) 555-0987",
    duration_seconds: 1200,
    disposition: "completed",
    notes: "Scheduled walkthrough. Client very interested, high-value project potential.",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    call_status: "completed",
    lead: { name: "Lisa Brown" },
  },
  {
    id: "demo-call-5",
    lead_id: "demo-lead-1",
    from_number: "(201) 555-0123",
    duration_seconds: 180,
    disposition: "callback",
    notes: "Brief intro call, client asked to call back after 5pm.",
    created_at: new Date().toISOString(),
    call_status: "completed",
    lead: { name: "Robert Anderson" },
  },
];

// Demo appointments for InsideSales
export const getDemoAppointments = () => [
  {
    id: "demo-appt-1",
    lead_id: "demo-lead-6",
    scheduled_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    appointment_type: "walkthrough",
    status: "scheduled",
    notes: "Initial walkthrough for whole home renovation",
    lead: { name: "Lisa Brown" },
  },
  {
    id: "demo-appt-2",
    lead_id: "demo-lead-3",
    scheduled_at: new Date(Date.now() + 4 * 86400000).toISOString(),
    appointment_type: "consultation",
    status: "scheduled",
    notes: "Review architectural plans for addition",
    lead: { name: "Michael Chen" },
  },
  {
    id: "demo-appt-3",
    lead_id: "demo-lead-2",
    scheduled_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    appointment_type: "consultation",
    status: "completed",
    notes: "Bathroom consultation completed, sending estimate",
    lead: { name: "Jennifer Martinez" },
  },
];

// Demo field visits for OutsideSales
export const getDemoFieldVisits = () => [
  {
    id: "demo-visit-1",
    lead_id: "demo-lead-6",
    lead_name: "Lisa Brown",
    address: "987 Cedar Lane, Summit, NJ",
    scheduled_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    status: "scheduled",
    outcome: "",
    notes: "Bring measurement tools, large renovation project",
  },
  {
    id: "demo-visit-2",
    lead_id: "demo-lead-3",
    lead_name: "Michael Chen",
    address: "789 Elm St, Montclair, NJ",
    scheduled_at: new Date(Date.now() + 4 * 86400000).toISOString(),
    status: "scheduled",
    outcome: "",
    notes: "Review architect plans on-site",
  },
  {
    id: "demo-visit-3",
    lead_id: "demo-lead-2",
    lead_name: "Jennifer Martinez",
    address: "456 Oak Ave, Paramus, NJ",
    scheduled_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: "completed",
    outcome: "estimate_sent",
    notes: "Measured bathroom, client approved premium fixtures",
  },
];

// Demo sales pipeline for SalesPipeline
export const getDemoSalesPipeline = () => [
  {
    id: "demo-pipeline-1",
    customer_name: "Lisa Brown",
    town: "Summit, NJ",
    amount: 185000,
    category: "Whole Home Renovation",
    lead_quality: "hot",
    probability: 75,
    status: "proposal_sent",
    sales_rep: "Mike Johnson",
    sales_rep_id: "rep-1",
    estimate_date: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "demo-pipeline-2",
    customer_name: "Michael Chen",
    town: "Montclair, NJ",
    amount: 125000,
    category: "Home Addition",
    lead_quality: "warm",
    probability: 60,
    status: "negotiating",
    sales_rep: "Sarah Williams",
    sales_rep_id: "rep-2",
    estimate_date: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "demo-pipeline-3",
    customer_name: "Robert Anderson",
    town: "Ridgewood, NJ",
    amount: 47500,
    category: "Kitchen Remodel",
    lead_quality: "cold",
    probability: 30,
    status: "new",
    sales_rep: "Mike Johnson",
    sales_rep_id: "rep-1",
    estimate_date: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "demo-pipeline-4",
    customer_name: "Jennifer Martinez",
    town: "Paramus, NJ",
    amount: 32000,
    category: "Bathroom Remodel",
    lead_quality: "hot",
    probability: 85,
    status: "won",
    sales_rep: "Sarah Williams",
    sales_rep_id: "rep-2",
    estimate_date: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "demo-pipeline-5",
    customer_name: "David Wilson",
    town: "Fort Lee, NJ",
    amount: 18500,
    category: "Deck & Patio",
    lead_quality: "warm",
    probability: 50,
    status: "proposal_sent",
    sales_rep: "Mike Johnson",
    sales_rep_id: "rep-1",
    estimate_date: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

// Demo foreman tasks for ForemanPortal
export const getDemoForemanTasks = () => [
  {
    id: "demo-task-1",
    task_title: "Install kitchen cabinets - Johnson",
    description: "Install upper and lower cabinets per layout plan. Ensure level and plumb.",
    status: "pending",
    priority: "high",
    location: "123 Oak Street, Ridgewood, NJ",
    project_id: "demo-proj-1",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "demo-task-2",
    task_title: "Rough plumbing inspection - Martinez",
    description: "Coordinate with inspector for rough plumbing inspection. All pipes must be visible.",
    status: "in_progress",
    priority: "high",
    location: "456 River Road, Hoboken, NJ",
    project_id: "demo-proj-2",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "demo-task-3",
    task_title: "Frame basement walls - Thompson",
    description: "Complete framing for basement partition walls. Review plans for electrical outlet locations.",
    status: "in_progress",
    priority: "medium",
    location: "789 Valley Road, Montclair, NJ",
    project_id: "demo-proj-3",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "demo-task-4",
    task_title: "Final walkthrough prep - Wilson",
    description: "Punch list items: touch-up paint, clean deck surface, seal wood.",
    status: "completed",
    priority: "medium",
    location: "321 Pine Lane, Wayne, NJ",
    project_id: "demo-proj-4",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "demo-task-5",
    task_title: "HVAC coordination - Thompson basement",
    description: "Meet with HVAC sub to review ductwork routing for basement zone.",
    status: "pending",
    priority: "medium",
    location: "789 Valley Road, Montclair, NJ",
    project_id: "demo-proj-3",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "demo-task-6",
    task_title: "Material delivery - Summit project",
    description: "Receive and inventory window delivery. Check for damage before signing.",
    status: "blocked",
    priority: "high",
    location: "892 Summit Ave, Summit, NJ",
    project_id: "demo-proj-6",
    blocked_reason: "Delivery delayed by supplier - rescheduled for tomorrow",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

// Demo purchase orders for PurchaseOrders
export const getDemoPurchaseOrders = () => [
  {
    id: "demo-po-1",
    po_number: "PO-2025-001",
    vendor_id: "vendor-1",
    project_id: "demo-proj-1",
    order_date: new Date(Date.now() - 10 * 86400000).toISOString(),
    expected_delivery: new Date(Date.now() + 3 * 86400000).toISOString(),
    actual_delivery: null,
    status: "ordered",
    total: 4250,
    approved_by: "admin",
    approved_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    vendors: { company_name: "Bergen County Lumber" },
  },
  {
    id: "demo-po-2",
    po_number: "PO-2025-002",
    vendor_id: "vendor-2",
    project_id: "demo-proj-2",
    order_date: new Date(Date.now() - 7 * 86400000).toISOString(),
    expected_delivery: new Date(Date.now() - 1 * 86400000).toISOString(),
    actual_delivery: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: "delivered",
    total: 2850,
    approved_by: "admin",
    approved_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    vendors: { company_name: "NJ Plumbing Supply" },
  },
  {
    id: "demo-po-3",
    po_number: "PO-2025-003",
    vendor_id: "vendor-3",
    project_id: "demo-proj-6",
    order_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    expected_delivery: new Date(Date.now() + 7 * 86400000).toISOString(),
    actual_delivery: null,
    status: "in_transit",
    total: 8500,
    approved_by: "admin",
    approved_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    vendors: { company_name: "Anderson Windows Direct" },
  },
  {
    id: "demo-po-4",
    po_number: "PO-2025-004",
    vendor_id: "vendor-4",
    project_id: "demo-proj-3",
    order_date: new Date().toISOString(),
    expected_delivery: new Date(Date.now() + 14 * 86400000).toISOString(),
    actual_delivery: null,
    status: "pending",
    total: 3200,
    approved_by: null,
    approved_at: null,
    created_at: new Date().toISOString(),
    vendors: { company_name: "Home Depot Pro" },
  },
];

// Demo warranty claims for ContractorWarranty
export const getDemoWarrantyClaims = () => [
  {
    id: "demo-claim-1",
    claim_number: "WC-2025-001",
    claim_status: "pending",
    priority: "high",
    reported_issue_title: "Leaking faucet in kitchen",
    next_action_due_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    project_id: "demo-proj-4",
  },
  {
    id: "demo-claim-2",
    claim_number: "WC-2025-002",
    claim_status: "in_progress",
    priority: "medium",
    reported_issue_title: "Cabinet door alignment issue",
    next_action_due_at: new Date(Date.now() + 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    project_id: "demo-proj-4",
  },
  {
    id: "demo-claim-3",
    claim_number: "WC-2025-003",
    claim_status: "resolved",
    priority: "low",
    reported_issue_title: "Touch-up paint needed on trim",
    next_action_due_at: null,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    project_id: "demo-proj-7",
  },
  {
    id: "demo-claim-4",
    claim_number: "WC-2025-004",
    claim_status: "pending",
    priority: "medium",
    reported_issue_title: "GFCI outlet not working in bathroom",
    next_action_due_at: new Date(Date.now() + 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    project_id: "demo-proj-9",
  },
];

// Demo subcontractor info for SubcontractorPortal
export const getDemoSubcontractorInfo = () => ({
  id: "demo-sub-1",
  user_id: "demo-user",
  company_name: "Elite Electrical Services",
  trade: "Electrical",
  status: "active",
  rating: 4.8,
  projects_completed: 47,
  phone: "(201) 555-1234",
  email: "info@eliteelectrical.com",
  license_number: "EL-12345",
  insurance_expiry: new Date(Date.now() + 180 * 86400000).toISOString(),
});

// Demo project assignments for SubcontractorPortal
export const getDemoProjectAssignments = () => [
  {
    id: "demo-assign-1",
    project_id: "demo-proj-1",
    role_on_project: "Electrical Rough-In & Finish",
    status: "active",
    start_date: new Date(Date.now() - 7 * 86400000).toISOString(),
    end_date: new Date(Date.now() + 14 * 86400000).toISOString(),
  },
  {
    id: "demo-assign-2",
    project_id: "demo-proj-3",
    role_on_project: "Basement Electrical Installation",
    status: "assigned",
    start_date: new Date(Date.now() + 7 * 86400000).toISOString(),
    end_date: new Date(Date.now() + 28 * 86400000).toISOString(),
  },
  {
    id: "demo-assign-3",
    project_id: "demo-proj-7",
    role_on_project: "Panel Upgrade & Wiring",
    status: "completed",
    start_date: new Date(Date.now() - 30 * 86400000).toISOString(),
    end_date: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

// Demo user settings for ContractorSettings
export const getDemoUserSettings = () => ({
  full_name: "John Smith",
  email: "john@democontractor.com",
  phone: "(201) 555-0001",
  company_name: "Smith Construction LLC",
  notifications: {
    email_notifications: true,
    sms_notifications: true,
    push_notifications: true,
    project_updates: true,
    bid_updates: true,
    warranty_updates: false,
  },
});

// Demo PM appointments for PMAppointmentsDashboard
export const getDemoPMAppointments = () => [
  {
    id: "demo-apt-pm-1",
    project_id: "demo-proj-1",
    purpose: "Site Inspection",
    requested_start: new Date(Date.now() + 2 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 2 * 86400000 + 3600000).toISOString(),
    proposed_start: null,
    proposed_end: null,
    final_start: null,
    final_end: null,
    status: "requested_by_homeowner",
    homeowner_note: "Would like to discuss cabinet installation progress",
    sub_note: null,
    pm_note: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    forwarded_to_user_id: null,
    forwarded_to_role: null,
    requested_by_user_id: "demo-homeowner-1",
    project: {
      id: "demo-proj-1",
      project_name: "Kitchen Renovation - Bergen County",
      location: "123 Oak Street, Ridgewood, NJ",
      client_name: "Johnson Family",
    },
    homeowner: {
      full_name: "Robert Johnson",
      email: "robert.johnson@email.com",
    },
    foreman: null,
  },
  {
    id: "demo-apt-pm-2",
    project_id: "demo-proj-3",
    purpose: "Plumbing Rough-In Review",
    requested_start: new Date(Date.now() + 3 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 3 * 86400000 + 3600000).toISOString(),
    proposed_start: new Date(Date.now() + 4 * 86400000).toISOString(),
    proposed_end: new Date(Date.now() + 4 * 86400000 + 3600000).toISOString(),
    final_start: null,
    final_end: null,
    status: "sub_countered",
    homeowner_note: "Need to verify bathroom layout changes",
    sub_note: "Original time conflicts with another job. Proposed alternative.",
    pm_note: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    forwarded_to_user_id: "demo-foreman-1",
    forwarded_to_role: "foreman",
    requested_by_user_id: "demo-homeowner-3",
    project: {
      id: "demo-proj-3",
      project_name: "Basement Finishing - Montclair",
      location: "789 Valley Road, Montclair, NJ",
      client_name: "Thompson Residence",
    },
    homeowner: {
      full_name: "Michael Thompson",
      email: "michael.thompson@email.com",
    },
    foreman: {
      full_name: "Mike Rodriguez",
      email: "mike.rodriguez@contractor.com",
    },
  },
  {
    id: "demo-apt-pm-3",
    project_id: "demo-proj-6",
    purpose: "Material Selection Meeting",
    requested_start: new Date(Date.now() + 5 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 5 * 86400000 + 7200000).toISOString(),
    proposed_start: null,
    proposed_end: null,
    final_start: null,
    final_end: null,
    status: "sent_to_sub",
    homeowner_note: "Want to finalize flooring and tile selections",
    sub_note: null,
    pm_note: "Forwarded to design lead",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    forwarded_to_user_id: "demo-design-1",
    forwarded_to_role: "design_lead",
    requested_by_user_id: "demo-homeowner-6",
    project: {
      id: "demo-proj-6",
      project_name: "Whole Home Renovation - Summit",
      location: "892 Summit Ave, Summit, NJ",
      client_name: "Anderson Family",
    },
    homeowner: {
      full_name: "Sarah Anderson",
      email: "sarah.anderson@email.com",
    },
    foreman: {
      full_name: "Lisa Chen",
      email: "lisa.chen@contractor.com",
    },
  },
];

// Demo project timelines and milestones for ContractorTimelines
export const getDemoProjectTimelines = () => {
  const baseDate = new Date();
  return {
    tasks: [
      {
        id: "demo-task-1",
        name: "Initial Planning & Design",
        startDate: new Date(baseDate.getTime() - 30 * 86400000),
        endDate: new Date(baseDate.getTime() - 15 * 86400000),
        progress: 100,
        color: "bg-blue-500",
        completed: true,
      },
      {
        id: "demo-task-2",
        name: "Permits & Approvals",
        startDate: new Date(baseDate.getTime() - 20 * 86400000),
        endDate: new Date(baseDate.getTime() - 5 * 86400000),
        progress: 100,
        color: "bg-green-500",
        completed: true,
      },
      {
        id: "demo-task-3",
        name: "Demolition & Site Prep",
        startDate: new Date(baseDate.getTime() - 5 * 86400000),
        endDate: new Date(baseDate.getTime() + 5 * 86400000),
        progress: 60,
        color: "bg-purple-500",
        completed: false,
      },
      {
        id: "demo-task-4",
        name: "Construction Phase",
        startDate: new Date(baseDate.getTime() + 5 * 86400000),
        endDate: new Date(baseDate.getTime() + 45 * 86400000),
        progress: 0,
        color: "bg-orange-500",
        completed: false,
      },
      {
        id: "demo-task-5",
        name: "Final Inspection & Cleanup",
        startDate: new Date(baseDate.getTime() + 45 * 86400000),
        endDate: new Date(baseDate.getTime() + 60 * 86400000),
        progress: 0,
        color: "bg-pink-500",
        completed: false,
      },
    ],
    milestones: [
      {
        id: "demo-ms-1",
        name: "Electrical Rough-In",
        date: new Date(baseDate.getTime() + 15 * 86400000),
        type: "trade" as const,
        iconName: "Zap",
        completed: false,
        description: "Electrical contractor to complete rough-in work",
      },
      {
        id: "demo-ms-2",
        name: "Plumbing Installation",
        date: new Date(baseDate.getTime() + 18 * 86400000),
        type: "trade" as const,
        iconName: "Droplet",
        completed: false,
        description: "Main plumbing fixtures installed",
      },
      {
        id: "demo-ms-3",
        name: "Cabinet Delivery",
        date: new Date(baseDate.getTime() + 25 * 86400000),
        type: "delivery" as const,
        iconName: "Package",
        completed: false,
        description: "Custom cabinets delivered",
      },
      {
        id: "demo-ms-4",
        name: "Final Inspection",
        date: new Date(baseDate.getTime() + 55 * 86400000),
        type: "inspection" as const,
        iconName: "CheckCircle",
        completed: false,
        description: "Final building inspection and approval",
      },
    ],
    notifications: [
      {
        id: "demo-notif-1",
        project_id: "demo-proj-1",
        contractor_id: "demo-contractor",
        notification_type: "homeowner_action_needed",
        title: "Cabinet Selection Required",
        message: "Please finalize your cabinet selection by end of week",
        recipient_email: "homeowner@email.com",
        recipient_name: "Johnson Family",
        due_date: new Date(baseDate.getTime() + 3 * 86400000).toISOString(),
        related_task_id: null,
        related_milestone_id: null,
        status: "pending",
        sent_at: null,
        acknowledged_at: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  };
};

// Demo project detail for ContractorProjectDetail
export const getDemoProjectDetail = (projectId: string) => {
  const projects = getDemoProjects();
  const project = projects.find(p => p.id === projectId) || projects[0];
  
  return {
    project: {
      id: project.id,
      project_name: project.name,
      client_name: project.client_name,
      project_type: project.project_type,
      location: project.address,
      description: `Comprehensive ${project.project_type.toLowerCase()} project including design, demolition, construction, and finishing work.`,
      estimated_value: project.amount,
      status: project.status,
      deadline: project.estimated_completion,
      created_at: project.start_date,
      updated_at: new Date().toISOString(),
      contractor_id: "demo-contractor",
      square_footage: Math.floor(Math.random() * 2000) + 500,
    },
    teamMembers: [
      {
        id: "demo-tm-1",
        user_id: "demo-user-1",
        role: "project_manager",
        title: "Project Manager",
        is_active: true,
        profiles: { full_name: "Mike Rodriguez", email: "mike@contractor.com", phone: "(201) 555-0002" },
      },
      {
        id: "demo-tm-2",
        user_id: "demo-user-2",
        role: "foreman",
        title: "Site Foreman",
        is_active: true,
        profiles: { full_name: "Carlos Martinez", email: "carlos@contractor.com", phone: "(201) 555-0003" },
      },
    ],
    documents: [
      {
        id: "demo-doc-1",
        file_name: "Project_Blueprint_v2.pdf",
        file_type: "application/pdf",
        file_size: 2500000,
        file_path: "demo/blueprints/blueprint_v2.pdf",
        document_type: "blueprint",
        description: "Updated floor plan with client revisions",
        created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
        uploaded_by: "demo-user-1",
      },
      {
        id: "demo-doc-2",
        file_name: "Building_Permit.pdf",
        file_type: "application/pdf",
        file_size: 850000,
        file_path: "demo/permits/permit.pdf",
        document_type: "permit",
        description: "Approved building permit",
        created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
        uploaded_by: "demo-user-1",
      },
    ],
    milestones: [
      {
        id: "demo-pm-1",
        milestone_name: "Demo Complete",
        milestone_date: new Date(Date.now() - 5 * 86400000).toISOString(),
        milestone_type: "major",
        description: "Demolition phase completed",
        completed: true,
      },
      {
        id: "demo-pm-2",
        milestone_name: "Framing Complete",
        milestone_date: new Date(Date.now() + 10 * 86400000).toISOString(),
        milestone_type: "major",
        description: "Structural framing completed",
        completed: false,
      },
    ],
  };
};

// Demo SmartPlan data for ContractorSmartPlan
export const getDemoSmartPlan = () => ({
  smartPlan: {
    id: "demo-smartplan-1",
    title: "Kitchen Remodel - Weekly Plan",
    template_type: "three_three_three" as const,
    notes: "Demo SmartPlan showing the 3/3/3 productivity method",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  items: [
    { id: "demo-sp-1", section: "today", content: "Review cabinet delivery timeline", is_done: true, order_index: 0 },
    { id: "demo-sp-2", section: "today", content: "Call electrician about panel upgrade", is_done: false, order_index: 1 },
    { id: "demo-sp-3", section: "today", content: "Submit permit revision request", is_done: false, order_index: 2 },
    { id: "demo-sp-4", section: "week", content: "Order countertop materials", is_done: false, order_index: 0 },
    { id: "demo-sp-5", section: "week", content: "Schedule plumbing rough-in inspection", is_done: true, order_index: 1 },
    { id: "demo-sp-6", section: "week", content: "Finalize tile selections with homeowner", is_done: false, order_index: 2 },
    { id: "demo-sp-7", section: "later", content: "Plan appliance installation sequence", is_done: false, order_index: 0 },
    { id: "demo-sp-8", section: "later", content: "Coordinate backsplash installation", is_done: false, order_index: 1 },
    { id: "demo-sp-9", section: "later", content: "Schedule final walkthrough", is_done: false, order_index: 2 },
  ],
});

// Demo data for ContractorProjectManagement page
export const getDemoManagedProjects = () => [
  {
    id: "demo-mgmt-1",
    name: "Kitchen Renovation - Bergen County",
    address: "123 Oak Street, Ridgewood, NJ",
    workflow_status: "in_progress",
    budget_estimate: 47500,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 86400000).toISOString(),
    next_action_id: 1,
    next_step_title: "Schedule cabinet installation",
    next_step_due_at: new Date(Date.now() + 172800000).toISOString(),
    next_step_status: "pending",
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "demo-mgmt-2",
    name: "Master Bathroom Remodel - Hoboken",
    address: "456 River Road, Hoboken, NJ",
    workflow_status: "pre_construction",
    budget_estimate: 32000,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 172800000).toISOString(),
    next_action_id: 2,
    next_step_title: "Finalize tile selections",
    next_step_due_at: new Date(Date.now() + 86400000).toISOString(),
    next_step_status: "in_progress",
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "demo-mgmt-3",
    name: "Basement Finishing - Montclair",
    address: "789 Valley Road, Montclair, NJ",
    workflow_status: "in_progress",
    budget_estimate: 65000,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 259200000).toISOString(),
    next_action_id: 3,
    next_step_title: "Electrical rough-in inspection",
    next_step_due_at: new Date(Date.now() + 345600000).toISOString(),
    next_step_status: "scheduled",
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "demo-mgmt-4",
    name: "Deck & Patio - Wayne",
    address: "321 Pine Lane, Wayne, NJ",
    workflow_status: "punchlist",
    budget_estimate: 18500,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 432000000).toISOString(),
    next_action_id: 4,
    next_step_title: "Final walkthrough with client",
    next_step_due_at: new Date(Date.now() + 604800000).toISOString(),
    next_step_status: "pending",
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: "demo-mgmt-5",
    name: "Home Addition - Ridgewood",
    address: "555 Maple Ave, Ridgewood, NJ",
    workflow_status: "contract_signed",
    budget_estimate: 125000,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 604800000).toISOString(),
    next_action_id: 5,
    next_step_title: "Submit permit application",
    next_step_due_at: new Date(Date.now() - 86400000).toISOString(),
    next_step_status: "overdue",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: "demo-mgmt-6",
    name: "Whole Home Renovation - Summit",
    address: "892 Summit Ave, Summit, NJ",
    workflow_status: "rfp_out",
    budget_estimate: 185000,
    contractor_role: "bidder",
    last_contact_at: null,
    next_action_id: 6,
    next_step_title: "Prepare bid proposal",
    next_step_due_at: new Date(Date.now() + 259200000).toISOString(),
    next_step_status: "pending",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "demo-mgmt-7",
    name: "Pool House Build - Short Hills",
    address: "78 Old Short Hills Rd, Short Hills, NJ",
    workflow_status: "intake",
    budget_estimate: 95000,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 86400000).toISOString(),
    next_action_id: 7,
    next_step_title: "Initial site assessment",
    next_step_due_at: new Date(Date.now() + 518400000).toISOString(),
    next_step_status: "scheduled",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "demo-mgmt-8",
    name: "Garage Conversion - Morristown",
    address: "145 Madison Ave, Morristown, NJ",
    workflow_status: "complete",
    budget_estimate: 42000,
    contractor_role: "general_contractor",
    last_contact_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    next_action_id: null,
    next_step_title: null,
    next_step_due_at: null,
    next_step_status: null,
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
];

// Demo data for ContractorRoleManagement page
export const getDemoRoleUsers = () => [
  {
    id: "demo-role-user-1",
    full_name: "John Smith",
    email: "abc12345...",
    roles: ["project_manager", "estimator"],
  },
  {
    id: "demo-role-user-2",
    full_name: "Maria Garcia",
    email: "def67890...",
    roles: ["estimator"],
  },
  {
    id: "demo-role-user-3",
    full_name: "Robert Lee",
    email: "ghi23456...",
    roles: ["foreman", "subcontractor"],
  },
  {
    id: "demo-role-user-4",
    full_name: "Emily Davis",
    email: "jkl78901...",
    roles: ["project_coordinator"],
  },
  {
    id: "demo-role-user-5",
    full_name: "Carlos Rodriguez",
    email: "mno34567...",
    roles: ["foreman"],
  },
  {
    id: "demo-role-user-6",
    full_name: "Sarah Chen",
    email: "pqr89012...",
    roles: ["project_coordinator", "estimator"],
  },
  {
    id: "demo-role-user-7",
    full_name: "Michael Brown",
    email: "stu45678...",
    roles: [],
  },
];

// Demo data for ContractorUserApplicants page
export const getDemoApplicants = () => ({
  estimator_applicants: [
    {
      id: "demo-est-app-1",
      name: "Jennifer Wilson",
      email: "jwilson@email.com",
      phone: "(555) 111-2222",
      years_experience: 8,
      specializations: ["Kitchen", "Bathroom", "Whole Home"],
      status: "pending",
      created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: "demo-est-app-2",
      name: "David Park",
      email: "dpark@email.com",
      phone: "(555) 333-4444",
      years_experience: 12,
      specializations: ["Commercial", "New Construction", "Additions"],
      status: "approved",
      created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      id: "demo-est-app-3",
      name: "Amanda Torres",
      email: "atorres@email.com",
      phone: "(555) 555-6666",
      years_experience: 5,
      specializations: ["Bathroom", "Basement"],
      status: "pending",
      created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: "demo-est-app-4",
      name: "Kevin O'Brien",
      email: "kobrien@email.com",
      phone: "(555) 777-8888",
      years_experience: 15,
      specializations: ["Historic Restoration", "Luxury Homes", "Kitchen"],
      status: "rejected",
      created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
  ],
  gc_applicants: [
    {
      id: "demo-gc-app-1",
      contact_name: "Michael Johnson",
      company_name: "Johnson Construction LLC",
      email: "mjohnson@jconstruction.com",
      phone: "(555) 222-3333",
      years_in_business: 15,
      specializations: ["Residential", "Commercial", "Renovations"],
      status: "pending",
      created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: "demo-gc-app-2",
      contact_name: "Lisa Martinez",
      company_name: "Martinez Home Builders",
      email: "lisa@martinezhb.com",
      phone: "(555) 444-5555",
      years_in_business: 20,
      specializations: ["New Construction", "Additions", "Green Building"],
      status: "approved",
      created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      id: "demo-gc-app-3",
      contact_name: "James Wright",
      company_name: "Wright Renovations Inc",
      email: "james@wrightreno.com",
      phone: "(555) 666-7777",
      years_in_business: 8,
      specializations: ["Kitchen", "Bathroom", "Basement"],
      status: "pending",
      created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ],
});

// Demo data for SubcontractorAppointments page
export const getDemoSubcontractorAppointments = () => [
  {
    id: "demo-sub-apt-1",
    status: "sent_to_sub",
    purpose: "site_visit",
    requested_start: new Date(Date.now() + 2 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 2 * 86400000 + 3600000).toISOString(),
    homeowner_note: "Please bring samples of flooring options. Side entrance is easiest access.",
    pm_note: "Client prefers morning appointments. Focus on kitchen and dining area.",
    proposed_start: null,
    proposed_end: null,
    sub_note: null,
    final_start: null,
    final_end: null,
    contractor_projects: {
      project_name: "Kitchen Renovation - Bergen County",
      client_name: "Johnson Family",
      location: "123 Oak Street, Ridgewood, NJ",
    },
  },
  {
    id: "demo-sub-apt-2",
    status: "sub_countered",
    purpose: "measurement",
    requested_start: new Date(Date.now() + 3 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 3 * 86400000 + 7200000).toISOString(),
    homeowner_note: "Need accurate measurements for custom cabinets.",
    pm_note: "Bring laser measuring equipment.",
    proposed_start: new Date(Date.now() + 4 * 86400000).toISOString(),
    proposed_end: new Date(Date.now() + 4 * 86400000 + 7200000).toISOString(),
    sub_note: "Original time conflicts with another appointment. Proposed alternative.",
    final_start: null,
    final_end: null,
    contractor_projects: {
      project_name: "Master Bathroom Remodel - Hoboken",
      client_name: "Martinez Family",
      location: "456 River Road, Hoboken, NJ",
    },
  },
  {
    id: "demo-sub-apt-3",
    status: "confirmed",
    purpose: "final_inspection",
    requested_start: new Date(Date.now() + 5 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 5 * 86400000 + 5400000).toISOString(),
    homeowner_note: "Looking forward to seeing the completed work!",
    pm_note: "Bring punchlist items checklist. Client is detail-oriented.",
    proposed_start: null,
    proposed_end: null,
    sub_note: null,
    final_start: new Date(Date.now() + 5 * 86400000).toISOString(),
    final_end: new Date(Date.now() + 5 * 86400000 + 5400000).toISOString(),
    contractor_projects: {
      project_name: "Deck & Patio - Wayne",
      client_name: "Wilson Family",
      location: "321 Pine Lane, Wayne, NJ",
    },
  },
  {
    id: "demo-sub-apt-4",
    status: "confirmed",
    purpose: "walkthrough",
    requested_start: new Date(Date.now() + 7 * 86400000).toISOString(),
    requested_end: new Date(Date.now() + 7 * 86400000 + 3600000).toISOString(),
    homeowner_note: null,
    pm_note: "Initial walkthrough for basement project. Discuss waterproofing options.",
    proposed_start: null,
    proposed_end: null,
    sub_note: null,
    final_start: new Date(Date.now() + 7 * 86400000).toISOString(),
    final_end: new Date(Date.now() + 7 * 86400000 + 3600000).toISOString(),
    contractor_projects: {
      project_name: "Basement Finishing - Montclair",
      client_name: "Thompson Residence",
      location: "789 Valley Road, Montclair, NJ",
    },
  },
];

// Demo data for TeamInvitations page
export const getDemoTeamInvitations = () => [
  {
    id: "demo-invite-1",
    email: "newestimator@email.com",
    role: "estimator",
    status: "pending",
    invitation_token: "demo-token-1",
    invited_by_name: "Demo Contractor",
    company_name: "Demo Construction LLC",
    expires_at: new Date(Date.now() + 7 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    accepted_at: null,
  },
  {
    id: "demo-invite-2",
    email: "projectmanager@email.com",
    role: "project_manager",
    status: "accepted",
    invitation_token: "demo-token-2",
    invited_by_name: "Demo Contractor",
    company_name: "Demo Construction LLC",
    expires_at: new Date(Date.now() + 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    accepted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "demo-invite-3",
    email: "foreman@email.com",
    role: "foreman",
    status: "pending",
    invitation_token: "demo-token-3",
    invited_by_name: "Demo Contractor",
    company_name: "Demo Construction LLC",
    expires_at: new Date(Date.now() + 5 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    accepted_at: null,
  },
  {
    id: "demo-invite-4",
    email: "expired@email.com",
    role: "subcontractor",
    status: "expired",
    invitation_token: "demo-token-4",
    invited_by_name: "Demo Contractor",
    company_name: "Demo Construction LLC",
    expires_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    accepted_at: null,
  },
  {
    id: "demo-invite-5",
    email: "coordinator@email.com",
    role: "project_coordinator",
    status: "cancelled",
    invitation_token: "demo-token-5",
    invited_by_name: "Demo Contractor",
    company_name: "Demo Construction LLC",
    expires_at: new Date(Date.now() + 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    accepted_at: null,
  },
];

// Demo invitation data for TeamJoin page
export const getDemoTeamJoinInvitation = () => ({
  id: "demo-join-invite-1",
  role: "estimator",
  company_name: "Demo Construction LLC",
  invited_by_name: "Demo Contractor",
  expires_at: new Date(Date.now() + 7 * 86400000).toISOString(),
  contractor_id: "demo-contractor-1",
  current_uses: 0,
  max_uses: 1,
});

// Demo Finance Dashboard Data
export const getDemoFinanceSnapshot = () => ({
  activeContracts: 8,
  depositsPending: 2,
  installmentsDue: 4,
  overduePayments: 1,
  unbilledCOs: 3,
  collectedThisMonth: 127500,
  outstandingAR: 245000,
  avgDaysToCollect: 18,
});

export const getDemoFinancingCases = () => [
  {
    id: "demo-fc-1",
    homeowner_name: "Johnson Family",
    lender: "GreenSky",
    loan_amount: 47500,
    status: "approved",
    next_action: "Ready for funding",
    projects: { project_name: "Kitchen Renovation", homeowner_name: "Johnson Family" },
  },
  {
    id: "demo-fc-2",
    homeowner_name: "Martinez Family",
    lender: "Hearth",
    loan_amount: 32000,
    status: "in_review",
    next_action: "Awaiting credit decision",
    projects: { project_name: "Bathroom Remodel", homeowner_name: "Martinez Family" },
  },
  {
    id: "demo-fc-3",
    homeowner_name: "Thompson Residence",
    lender: "Affirm",
    loan_amount: 65000,
    status: "funded",
    next_action: null,
    projects: { project_name: "Basement Finishing", homeowner_name: "Thompson Residence" },
  },
  {
    id: "demo-fc-4",
    homeowner_name: "Chen Family",
    lender: "Service Finance",
    loan_amount: 125000,
    status: "pending",
    next_action: "Application submitted",
    projects: { project_name: "Home Addition", homeowner_name: "Chen Family" },
  },
];

export const getDemoUnbilledChangeOrders = () => [
  {
    id: "demo-co-1",
    change_order_number: "CO-2025-001",
    project_name: "Kitchen Renovation",
    description: "Upgraded countertops to quartz",
    change_amount: 3500,
    contractor_projects: { project_name: "Kitchen Renovation", homeowner_name: "Johnson Family" },
  },
  {
    id: "demo-co-2",
    change_order_number: "CO-2025-002",
    project_name: "Basement Finishing",
    description: "Added bathroom rough-in",
    change_amount: 8200,
    contractor_projects: { project_name: "Basement Finishing", homeowner_name: "Thompson Residence" },
  },
  {
    id: "demo-co-3",
    change_order_number: "CO-2025-003",
    project_name: "Whole Home Renovation",
    description: "Electrical panel upgrade",
    change_amount: 4800,
    contractor_projects: { project_name: "Whole Home Renovation", homeowner_name: "Anderson Family" },
  },
];

export const getDemoBillingPipeline = () => [
  {
    id: "demo-contract-1",
    project_id: "demo-proj-1",
    project_name: "Kitchen Renovation - Bergen County",
    homeowner_name: "Johnson Family",
    stage: "in_progress",
    contract_status: "signed" as const,
    deposit_status: "paid" as const,
    next_installment_date: new Date(Date.now() + 7 * 86400000).toISOString(),
    balance: 28500,
    billing_status: "due_soon" as const,
  },
  {
    id: "demo-contract-2",
    project_id: "demo-proj-2",
    project_name: "Master Bathroom Remodel",
    homeowner_name: "Martinez Family",
    stage: "planning",
    contract_status: "signed" as const,
    deposit_status: "pending" as const,
    next_installment_date: null,
    balance: 32000,
    billing_status: "blocked" as const,
  },
  {
    id: "demo-contract-3",
    project_id: "demo-proj-3",
    project_name: "Basement Finishing",
    homeowner_name: "Thompson Residence",
    stage: "in_progress",
    contract_status: "signed" as const,
    deposit_status: "paid" as const,
    next_installment_date: new Date(Date.now() + 21 * 86400000).toISOString(),
    balance: 45500,
    billing_status: "current" as const,
  },
  {
    id: "demo-contract-4",
    project_id: "demo-proj-4",
    project_name: "Deck & Patio",
    homeowner_name: "Wilson Family",
    stage: "complete",
    contract_status: "signed" as const,
    deposit_status: "paid" as const,
    next_installment_date: null,
    balance: 0,
    billing_status: "paid" as const,
  },
  {
    id: "demo-contract-5",
    project_id: "demo-proj-5",
    project_name: "Home Addition",
    homeowner_name: "Chen Family",
    stage: "pending",
    contract_status: "sent" as const,
    deposit_status: "pending" as const,
    next_installment_date: null,
    balance: 125000,
    billing_status: "blocked" as const,
  },
  {
    id: "demo-contract-6",
    project_id: "demo-proj-6",
    project_name: "Whole Home Renovation",
    homeowner_name: "Anderson Family",
    stage: "in_progress",
    contract_status: "signed" as const,
    deposit_status: "paid" as const,
    next_installment_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    balance: 148000,
    billing_status: "blocked" as const,
  },
];
