// Demo data generator for bid comparison examples

export const generateDemoKitchenRemodel = () => {
  const opportunityId = "demo-kitchen-remodel-2025";
  const projectId = null; // Can be linked to actual project if needed

  return {
    opportunityId,
    projectId,
    opportunityTitle: "Modern Kitchen Renovation - Bergen County",
    bids: [
      {
        id: "bid-contractor-1",
        bidder_id: "contractor-1-demo",
        bid_amount: 47500,
        estimated_timeline: "8-10 weeks",
        years_in_business: 15,
        crew_size: 8,
        has_project_manager: true,
        platform_ratings: {
          google: 4.8,
          yelp: 4.7,
          angi: 4.9,
          houzz: 4.8,
        },
        overall_rating: 4.8,
        anticipated_start_date: "2025-02-15",
        project_duration_weeks: 9,
        insurance_verified: true,
        workers_comp_verified: true,
        license_verified: true,
        warranty_years: 5,
        warranty_terms: "5-year comprehensive warranty on all workmanship and materials. Includes 1-year full service guarantee.",
        references_count: 12,
        portfolio_projects_count: 87,
        certifications: [
          { name: "NKBA Certified", issuer: "National Kitchen & Bath Association", year: 2020 },
          { name: "Lead-Safe Certified", issuer: "EPA", year: 2019 },
        ],
        bidder_type: "contractor",
        status: "submitted",
        profiles: {
          full_name: "Elite Home Renovations LLC",
        },
      },
      {
        id: "bid-contractor-2",
        bidder_id: "contractor-2-demo",
        bid_amount: 52000,
        estimated_timeline: "6-8 weeks",
        years_in_business: 22,
        crew_size: 12,
        has_project_manager: true,
        platform_ratings: {
          google: 4.9,
          yelp: 4.8,
          angi: 5.0,
          houzz: 4.9,
        },
        overall_rating: 4.9,
        anticipated_start_date: "2025-02-01",
        project_duration_weeks: 7,
        insurance_verified: true,
        workers_comp_verified: true,
        license_verified: true,
        warranty_years: 10,
        warranty_terms: "10-year structural warranty, 5-year workmanship warranty, 2-year full-service guarantee with priority scheduling.",
        references_count: 24,
        portfolio_projects_count: 156,
        certifications: [
          { name: "NARI Certified Remodeler", issuer: "National Association of Remodeling Industry", year: 2018 },
          { name: "CGP - Certified Green Professional", issuer: "NAHB", year: 2020 },
          { name: "NKBA Certified", issuer: "National Kitchen & Bath Association", year: 2017 },
        ],
        bidder_type: "contractor",
        status: "submitted",
        profiles: {
          full_name: "Premier Kitchen & Bath Experts",
        },
      },
      {
        id: "bid-contractor-3",
        bidder_id: "contractor-3-demo",
        bid_amount: 43900,
        estimated_timeline: "10-12 weeks",
        years_in_business: 8,
        crew_size: 5,
        has_project_manager: false,
        platform_ratings: {
          google: 4.6,
          yelp: 4.5,
          angi: 4.7,
          houzz: 4.6,
        },
        overall_rating: 4.6,
        anticipated_start_date: "2025-03-01",
        project_duration_weeks: 11,
        insurance_verified: true,
        workers_comp_verified: true,
        license_verified: true,
        warranty_years: 3,
        warranty_terms: "3-year warranty on workmanship, manufacturer warranties on all materials and appliances.",
        references_count: 8,
        portfolio_projects_count: 34,
        certifications: [
          { name: "EPA Lead-Safe Certified", issuer: "EPA", year: 2021 },
        ],
        bidder_type: "contractor",
        status: "submitted",
        profiles: {
          full_name: "Quality Home Builders Co.",
        },
      },
    ],
  };
};

export const generateDemoBathroomRemodel = () => {
  return {
    opportunityId: "demo-bathroom-remodel-2025",
    projectId: null,
    opportunityTitle: "Master Bathroom Renovation - Hoboken",
    bids: [
      {
        id: "bid-bath-1",
        bidder_id: "contractor-bath-1",
        bid_amount: 28500,
        estimated_timeline: "4-6 weeks",
        years_in_business: 18,
        crew_size: 6,
        has_project_manager: true,
        platform_ratings: { google: 4.8, yelp: 4.7, angi: 4.9, houzz: 4.8 },
        overall_rating: 4.8,
        anticipated_start_date: "2025-02-20",
        project_duration_weeks: 5,
        insurance_verified: true,
        workers_comp_verified: true,
        license_verified: true,
        warranty_years: 5,
        warranty_terms: "5-year workmanship warranty, lifetime warranty on plumbing fixtures",
        references_count: 15,
        portfolio_projects_count: 92,
        certifications: [{ name: "NKBA Certified", issuer: "NKBA", year: 2019 }],
        bidder_type: "contractor",
        status: "submitted",
        profiles: { full_name: "Bathroom Specialists Inc." },
      },
      {
        id: "bid-bath-2",
        bidder_id: "contractor-bath-2",
        bid_amount: 32000,
        estimated_timeline: "3-4 weeks",
        years_in_business: 25,
        crew_size: 8,
        has_project_manager: true,
        platform_ratings: { google: 5.0, yelp: 4.9, angi: 5.0, houzz: 5.0 },
        overall_rating: 4.975,
        anticipated_start_date: "2025-02-10",
        project_duration_weeks: 4,
        insurance_verified: true,
        workers_comp_verified: true,
        license_verified: true,
        warranty_years: 7,
        warranty_terms: "7-year comprehensive warranty with annual maintenance included",
        references_count: 28,
        portfolio_projects_count: 183,
        certifications: [
          { name: "Master Plumber License", issuer: "NJ Board", year: 2015 },
          { name: "NARI Certified", issuer: "NARI", year: 2016 },
        ],
        bidder_type: "contractor",
        status: "submitted",
        profiles: { full_name: "Luxury Bath Remodeling" },
      },
    ],
  };
};
