import { useState } from "react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Search, Home, DollarSign, Calendar } from "lucide-react";
import { format } from "date-fns";

export default function AdminPropertyReports() {
  const [search, setSearch] = useState("");

  const { data: reports, isLoading } = useQuery({
    queryKey: ["admin-property-reports"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("property_reports" as any)
        .select("*")
        .order("created_at", { ascending: false })
        .limit(200);
      if (error) throw error;
      return data as any[];
    },
  });

  const filtered = reports?.filter((r) =>
    !search ||
    r.address?.toLowerCase().includes(search.toLowerCase()) ||
    r.city?.toLowerCase().includes(search.toLowerCase()) ||
    r.zip?.includes(search)
  );

  const totalReports = reports?.length || 0;
  const convertedCount = reports?.filter((r) => r.converted_to_project_id).length || 0;
  const avgCostLow = reports?.length
    ? Math.round(reports.reduce((sum, r) => sum + (r.estimated_cost_low || 0), 0) / reports.length)
    : 0;

  return (
    <AdminLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Property Reports</h1>
          <p className="text-muted-foreground">Renovation cost evaluations generated by homeowners</p>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Total Reports", value: totalReports, icon: Home },
            { label: "Converted to Projects", value: convertedCount, icon: Calendar },
            { label: "Conversion Rate", value: totalReports ? `${Math.round((convertedCount / totalReports) * 100)}%` : "0%", icon: DollarSign },
            { label: "Avg Est. (Low)", value: avgCostLow ? `$${avgCostLow.toLocaleString()}` : "$0", icon: DollarSign },
          ].map((s) => (
            <Card key={s.label} className="border-border">
              <CardContent className="p-4">
                <div className="flex items-center gap-3">
                  <div className="h-10 w-10 rounded-lg bg-muted flex items-center justify-center">
                    <s.icon className="h-5 w-5 text-muted-foreground" />
                  </div>
                  <div>
                    <p className="text-xl font-bold text-foreground">{s.value}</p>
                    <p className="text-xs text-muted-foreground">{s.label}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Search */}
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search by address, city, or zip..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>

        {/* Table */}
        <Card className="border-border">
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Address</TableHead>
                  <TableHead>City</TableHead>
                  <TableHead>Sq Ft</TableHead>
                  <TableHead>Scopes</TableHead>
                  <TableHead>Est. Range</TableHead>
                  <TableHead>Converted</TableHead>
                  <TableHead>Date</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                      Loading reports...
                    </TableCell>
                  </TableRow>
                ) : filtered?.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                      No property reports found
                    </TableCell>
                  </TableRow>
                ) : (
                  filtered?.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium">{report.address || "—"}</TableCell>
                      <TableCell>{report.city || "—"}</TableCell>
                      <TableCell>{report.square_feet?.toLocaleString() || "—"}</TableCell>
                      <TableCell>
                        {report.selected_scopes?.length ? (
                          <Badge variant="secondary">{report.selected_scopes.length} selected</Badge>
                        ) : (
                          <span className="text-muted-foreground">—</span>
                        )}
                      </TableCell>
                      <TableCell>
                        {report.estimated_cost_low && report.estimated_cost_high ? (
                          <span className="text-sm">
                            ${report.estimated_cost_low.toLocaleString()} – ${report.estimated_cost_high.toLocaleString()}
                          </span>
                        ) : (
                          "—"
                        )}
                      </TableCell>
                      <TableCell>
                        {report.converted_to_project_id ? (
                          <Badge className="bg-accent text-accent-foreground">Yes</Badge>
                        ) : (
                          <Badge variant="outline">No</Badge>
                        )}
                      </TableCell>
                      <TableCell className="text-muted-foreground text-sm">
                        {format(new Date(report.created_at), "MMM d, yyyy")}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </AdminLayout>
  );
}
